// Fehlvorstellungen (Stolpersteine) zum Atombau – Schlüssel für diagnostische Distraktoren und Fallen in Eingabe-Aufgaben.
// Die Rückmeldungstexte stehen bei den Aufgaben (mit den konkreten Zahlen); hier nur der Name für Landkarte und Auswertung.

export const MISS: Record<string, string> = {
  "massenzahl-elektronen": "Massenzahl mit Elektronenzahl verwechselt",
  "massenzahl-ordnungszahl": "Massenzahl und Ordnungszahl verwechselt",
  "massenzahl-neutronen": "Massenzahl mit Neutronenzahl verwechselt",
  "elektronen-mitgezaehlt": "Elektronen zur Massenzahl gezählt",
  "neutronen-massenzahl": "Neutronen = Massenzahl (Protonen nicht abgezogen)",
  "neutronen-protonen": "Neutronen = Protonen angenommen",
  "ion-ladung-ignoriert": "Ladung des Ions ignoriert",
  "ladung-vorzeichen": "Vorzeichen der Ladung verdreht",
  "ladung-neutral": "Geladenes Teilchen für neutral gehalten",
  "aussen-periode": "Außenelektronen mit Periode verwechselt",
  "aussen-ordnungszahl": "Außenelektronen mit Ordnungszahl verwechselt",
  "aussen-fehlend": "Fehlende statt vorhandene Außenelektronen gezählt",
  "schalen-gruppe": "Schalenzahl mit Hauptgruppe verwechselt",
  "schalen-je-8": "Alle Schalen mit 8 Elektronen gerechnet",
  "leere-schale-gezaehlt": "Leere Schale mitgezählt",
  "nur-aussenschale": "Nur die äußerste Schale gezählt",
  "k-schale-ueberfuellt": "K-Schale mit mehr als 2 Elektronen",
  "l-schale-ueberfuellt": "L-Schale mit mehr als 8 Elektronen",
  "ion-gegenteil": "Metall als Anion / Nichtmetall als Kation",
  "auffuellen-statt-abgeben": "Metall füllt auf statt abzugeben",
  "abgeben-statt-aufnehmen": "Nichtmetall gibt ab statt aufzunehmen",
  "isotop-element": "Isotope für verschiedene Elemente gehalten",
  "isotop-elektronen": "Isotope: Elektronen statt Neutronen",
  "isotop-neutronen-gleich": "Isotope: gleiche Neutronenzahl angenommen",
  "isotop-massenzahl-gleich": "Isotope: gleiche Massenzahl angenommen",
  "3d-vor-4s": "3d vor 4s befüllt (Energie statt n)",
  "edelgaskern-falsch": "Falsches Edelgas als Kern",
  "elektronen-verzaehlt": "Elektronen verzählt",
  "hund-alle-einzeln": "Hund'sche Regel: alle als ungepaart gezählt",
  "hund-alle-gepaart": "Hund'sche Regel: alle als gepaart gezählt",
  "ion-3d-zuerst": "Kation: 3d- statt 4s-Elektronen abgegeben",
  "periode-n": "Periode ≠ höchste Hauptquantenzahl",
  "hauptgruppe-vs-gruppe": "Hauptgruppe und Gruppennummer verwechselt",
  "protonen-massenzahl": "Protonenzahl mit der Massenzahl verwechselt",
  "schalen-statt-elektronen": "Schalen statt Elektronen gezählt",
  "block-letzte-geschrieben": "Block nach der zuletzt geschriebenen statt zuletzt befüllten Unterschale",
  "edelgaskern-vergessen": "Edelgaskern beim Zählen vergessen",
};
