// Fehlvorstellungen (Stolpersteine) zum Atombau – Schlüssel für diagnostische Distraktoren und Fallen in Eingabe-Aufgaben.
// Die Rückmeldungstexte stehen bei den Aufgaben (mit den konkreten Zahlen); hier nur der Name für Landkarte und Auswertung.
import { tr } from "@lern/i18n";

const MISS_DE: Record<string, string> = {
  "massenzahl-elektronen": "Massenzahl mit Elektronenzahl verwechselt",
  "massenzahl-ordnungszahl": "Massenzahl und Ordnungszahl verwechselt",
  "massenzahl-neutronen": "Massenzahl mit Neutronenzahl verwechselt",
  "elektronen-mitgezaehlt": "Elektronen zur Massenzahl gezählt",
  "neutronen-massenzahl": "Neutronen = Massenzahl (Protonen nicht abgezogen)",
  "neutronen-protonen": "Neutronen = Protonen angenommen",
  "ion-ladung-ignoriert": "Ladung des Ions ignoriert",
  "ladung-vorzeichen": "Vorzeichen der Ladung verdreht",
  "ladung-neutral": "Geladenes Teilchen für neutral gehalten",
  "aussen-periode": "Außenelektronen mit Periode verwechselt",
  "aussen-ordnungszahl": "Außenelektronen mit Ordnungszahl verwechselt",
  "aussen-fehlend": "Fehlende statt vorhandene Außenelektronen gezählt",
  "helium-acht": "Helium wie die übrigen Edelgase mit 8 Außenelektronen gezählt",
  "kapazitaet-statt-anzahl": "Platz auf der Schale statt vorhandener Elektronen gezählt",
  "schalen-gruppe": "Schalenzahl mit Hauptgruppe verwechselt",
  "schalen-je-8": "Alle Schalen mit 8 Elektronen gerechnet",
  "leere-schale-gezaehlt": "Leere Schale mitgezählt",
  "nur-aussenschale": "Nur die äußerste Schale gezählt",
  "k-schale-ueberfuellt": "K-Schale mit mehr als 2 Elektronen",
  "l-schale-ueberfuellt": "L-Schale mit mehr als 8 Elektronen",
  "ion-gegenteil": "Metall als Anion / Nichtmetall als Kation",
  "auffuellen-statt-abgeben": "Metall füllt auf statt abzugeben",
  "abgeben-statt-aufnehmen": "Nichtmetall gibt ab statt aufzunehmen",
  "isotop-element": "Isotope für verschiedene Elemente gehalten",
  "isotop-elektronen": "Isotope: Elektronen statt Neutronen",
  "isotop-neutronen-gleich": "Isotope: gleiche Neutronenzahl angenommen",
  "isotop-massenzahl-gleich": "Isotope: gleiche Massenzahl angenommen",
  "3d-vor-4s": "3d vor 4s befüllt (n statt Energie)",
  "edelgaskern-falsch": "Falsches Edelgas als Kern",
  "elektronen-verzaehlt": "Elektronen verzählt",
  "hund-alle-einzeln": "Hund'sche Regel: alle als ungepaart gezählt",
  "hund-alle-gepaart": "Hund'sche Regel: alle als gepaart gezählt",
  "ion-3d-zuerst": "Kation: 3d- statt 4s-Elektronen abgegeben",
  "periode-n": "Periode ≠ höchste Hauptquantenzahl",
  "hauptgruppe-vs-gruppe": "Hauptgruppe und Gruppennummer verwechselt",
  "protonen-massenzahl": "Protonenzahl mit der Massenzahl verwechselt",
  "schalen-statt-elektronen": "Schalen statt Elektronen gezählt",
  "block-letzte-geschrieben": "Block nach der zuletzt geschriebenen statt zuletzt befüllten Unterschale",
  "edelgaskern-vergessen": "Edelgaskern beim Zählen vergessen",
};
const MISS_EN: Record<string, string> = {
  "massenzahl-elektronen": "Mass number confused with electron count",
  "massenzahl-ordnungszahl": "Mass number and atomic number confused",
  "massenzahl-neutronen": "Mass number confused with neutron count",
  "elektronen-mitgezaehlt": "Electrons counted in the mass number",
  "neutronen-massenzahl": "Neutrons = mass number (protons not subtracted)",
  "neutronen-protonen": "Assumed neutrons = protons",
  "ion-ladung-ignoriert": "Charge of the ion ignored",
  "ladung-vorzeichen": "Sign of the charge reversed",
  "ladung-neutral": "Charged particle taken as neutral",
  "aussen-periode": "Outer electrons confused with period",
  "aussen-ordnungszahl": "Outer electrons confused with atomic number",
  "aussen-fehlend": "Counted missing instead of existing outer electrons",
  "helium-acht": "Helium counted with 8 outer electrons like the other noble gases",
  "kapazitaet-statt-anzahl": "Counted the room on the shell instead of the electrons there",
  "schalen-gruppe": "Number of shells confused with main group",
  "schalen-je-8": "Every shell counted with 8 electrons",
  "leere-schale-gezaehlt": "Empty shell counted",
  "nur-aussenschale": "Only the outer shell counted",
  "k-schale-ueberfuellt": "K shell with more than 2 electrons",
  "l-schale-ueberfuellt": "L shell with more than 8 electrons",
  "ion-gegenteil": "Metal as anion / non-metal as cation",
  "auffuellen-statt-abgeben": "Metal gains instead of losing electrons",
  "abgeben-statt-aufnehmen": "Non-metal loses instead of gaining electrons",
  "isotop-element": "Isotopes taken as different elements",
  "isotop-elektronen": "Isotopes: electrons instead of neutrons",
  "isotop-neutronen-gleich": "Isotopes: assumed same neutron count",
  "isotop-massenzahl-gleich": "Isotopes: assumed same mass number",
  "3d-vor-4s": "3d filled before 4s (n instead of energy)",
  "edelgaskern-falsch": "Wrong noble gas as core",
  "elektronen-verzaehlt": "Electrons miscounted",
  "hund-alle-einzeln": "Hund's rule: all counted as unpaired",
  "hund-alle-gepaart": "Hund's rule: all counted as paired",
  "ion-3d-zuerst": "Cation: 3d instead of 4s electrons removed",
  "periode-n": "Period ≠ highest principal quantum number",
  "hauptgruppe-vs-gruppe": "Main group and group number confused",
  "protonen-massenzahl": "Proton number confused with mass number",
  "schalen-statt-elektronen": "Counted shells instead of electrons",
  "block-letzte-geschrieben": "Block from the subshell written last instead of filled last",
  "edelgaskern-vergessen": "Noble gas core forgotten when counting",
};
export const MISS = tr(MISS_DE, MISS_EN);
