// Fehlvorstellungen (Stolpersteine) zu Reinstoffen, Gemischen und zum Teilchenmodell – Schlüssel für diagnostische
// Distraktoren und Fallen. Die Rückmeldungstexte stehen bei den Aufgaben (mit den konkreten Stoffen); hier nur der Name
// für Landkarte und Auswertung.
import { tr } from "@lern/i18n";

const MISS_DE: Record<string, string> = {
  // Teilchen und Stoffe zählen
  "atome-gezaehlt": "Atome statt Teilchen gezählt",
  "stoffe-statt-teilchen": "Stoffe statt Teilchen gezählt",
  "teilchen-statt-stoffe": "Teilchen statt Stoffe gezählt",
  "atomsorten-statt-stoffe": "Atomsorten statt Stoffe gezählt",
  "stoffe-statt-atomsorten": "Stoffe statt Atomsorten gezählt",
  "sorten-uebersehen": "Verschiedene Teilchensorten übersehen",
  // Element, Verbindung, Gemisch
  "verbindung-gemisch": "Verbindung für Gemisch gehalten",
  "verbindung-element": "Verbindung für Element gehalten",
  "element-verbindung": "Element für Verbindung gehalten",
  "element-molekuel": "Element aus Molekülen für Verbindung gehalten",
  "gemisch-verbindung": "Gemisch aus Elementen für Verbindung gehalten",
  "nur-elemente-rein": "Gemisch aus Elementen für Reinstoff gehalten",
  // Gemische im Alltag
  "klar-reinstoff": "Klares Gemisch für Reinstoff gehalten",
  "geloest-heterogen": "Lösung für heterogen gehalten",
  "sieht-einheitlich": "Fein verteiltes Gemisch für homogen gehalten",
  "entmischt-homogen": "Entmischtes Gemisch für homogen gehalten",
  "zustand-verwechselt": "Zustände im Gemisch verwechselt",
  // ohne „Legierung“: kommt schon in Kapitel 3 vor (Messing nach dem Erstarren), der Begriff erst in Kapitel 4
  "legierung-verbindung": "Gemischte Metalle für Verbindung gehalten",
  "legierung-gemenge": "Legierung und Gemenge verwechselt",
  "alltag-rein": "„Rein“ im Alltag für Reinstoff gehalten",
  // Lösen und Mischen im Teilchenmodell
  "verschwindet": "Gelöster Stoff verschwindet",
  "kristall-bleibt": "Gelöster Stoff bleibt als Kristall",
  "loesen-schmelzen": "Lösen mit Schmelzen verwechselt",
  "teilchen-veraendert": "Teilchen ändern sich beim Mischen",
  "geloest-unten": "Gemischter Stoff sammelt sich unten",
  "masse-aendert": "Masse ändert sich beim Lösen",
  "luft-dazwischen": "Etwas zwischen den Teilchen vermutet",
  "teilchen-ruhen": "Teilchen ruhen ohne Rühren",
  "teilchen-wie-stoff": "Eigenschaften des Stoffs auf Teilchen übertragen",
  "modell-echt": "Modellfarben für echt gehalten",
  "oel-mischt": "Öl und Wasser bleiben gemischt",
  "oel-unten": "Öl für schwerer als Wasser gehalten",
  // Stofftrennung
  "filter-geloest": "Gelöstes für filtrierbar gehalten",
  "teil-verwechselt": "Teile nach dem Trennen verwechselt",
  "reihenfolge": "Reihenfolge der Trennschritte vertauscht",
};
const MISS_EN: Record<string, string> = {
  "atome-gezaehlt": "Counted atoms instead of particles",
  "stoffe-statt-teilchen": "Counted substances instead of particles",
  "teilchen-statt-stoffe": "Counted particles instead of substances",
  "atomsorten-statt-stoffe": "Counted kinds of atom instead of substances",
  "stoffe-statt-atomsorten": "Counted substances instead of kinds of atom",
  "sorten-uebersehen": "Different kinds of particle overlooked",
  "verbindung-gemisch": "Compound taken for a mixture",
  "verbindung-element": "Compound taken for an element",
  "element-verbindung": "Element taken for a compound",
  "element-molekuel": "Element made of molecules taken for a compound",
  "gemisch-verbindung": "Mixture of elements taken for a compound",
  "nur-elemente-rein": "Mixture of elements taken for a pure substance",
  "klar-reinstoff": "Clear mixture taken for a pure substance",
  "geloest-heterogen": "Solution taken for heterogeneous",
  "sieht-einheitlich": "Finely dispersed mixture taken for homogeneous",
  "entmischt-homogen": "Separated mixture taken for homogeneous",
  "zustand-verwechselt": "States in the mixture confused",
  "legierung-verbindung": "Mixed metals taken for a compound",
  "legierung-gemenge": "Alloy and coarse mixture confused",
  "alltag-rein": "Everyday “pure” taken for pure substance",
  "verschwindet": "Dissolved substance disappears",
  "kristall-bleibt": "Dissolved substance stays a crystal",
  "loesen-schmelzen": "Dissolving confused with melting",
  "teilchen-veraendert": "Particles change when mixing",
  "geloest-unten": "Mixed substance collects at the bottom",
  "masse-aendert": "Mass changes on dissolving",
  "luft-dazwischen": "Something assumed between the particles",
  "teilchen-ruhen": "Particles at rest without stirring",
  "teilchen-wie-stoff": "Properties of the substance given to particles",
  "modell-echt": "Model colours taken as real",
  "oel-mischt": "Oil and water stay mixed",
  "oel-unten": "Oil thought heavier than water",
  "filter-geloest": "Dissolved substance thought to be filterable",
  "teil-verwechselt": "Parts mixed up after separating",
  "reihenfolge": "Separation steps in the wrong order",
};
export const MISS = tr(MISS_DE, MISS_EN);
