// Kapitel 5: Nebengruppenmetalle (Level II) – ohne Elektronenkonfiguration und ohne Auswendiglernen:
// gleiche Elemente, verschiedene Stoffe (FeO/Fe₂O₃, Cu₂O/CuO) → die Ladung des Metall-Ions muss in den Namen; im PSE liest man sie nur bei
// den Metallen der I. bis III. Hauptgruppe (Gruppe 1, 2, 13) ab, bei allen anderen steht sie als römische Zahl im Namen. Dann Name → Formel,
// Formel → Name, mit mehratomigen Ionen. Begründet wird nur über Ladungsbilanz und Namen (nie „gibt es nicht“). Nur Fe, Cu und Pb(II) aus `ions.ts`.
// Texte nennen Ladungen in Worten („drei positive Ladungen“) – keine Rechnung mit Klammern, keine Breiten oder Reihen der Bausteine.

import { tr } from "@lern/i18n";
import type { GuideStep } from "@lern/ui";
import type { Kapitel } from "./types.ts";
import { model } from "./model.tsx";
import { GroupStrip, OxidePair, PseMetals, WallModel, pseWhy, wallWhy } from "./k5/models.tsx";
import "./k5/k5.css";

const NE = (de: string, en: string) => tr(de, en);

// Metalle für das PSE (Ordnungszahlen)
const LI = 3, MG = 12, AL = 13, K = 19, CA = 20, FE = 26, CU = 29, BA = 56, PB = 82;
const PSE_A = [LI, AL, CA, FE, CU], PSE_B = [AL, K, FE, CU, BA, PB];

const steps = (): GuideStep[] => [
  // ── 1. Ein Metall – mehrere Ionen ──
  model({
    mode: "worked", part: NE("Ein Metall – mehrere Ionen", "One metal – several ions"),
    say: NE("Eisen und Sauerstoff bilden zwei verschiedene Stoffe. **FeO** ist ein schwarzes Pulver, **Fe₂O₃** ist rotbraun wie Rost.",
      "Iron and oxygen form two different substances. **FeO** is a black powder, **Fe₂O₃** is red-brown like rust."),
    ask: NE("Warum reicht der Name „Eisenoxid“ nicht aus?", "Why is the name “iron oxide” not enough?"),
    lines: [
      NE("In FeO gleicht ein Oxid-Ion O²⁻ genau ein Eisen-Ion aus. Das Eisen-Ion trägt also zwei positive Ladungen: Fe²⁺.",
        "In FeO one oxide ion O²⁻ balances exactly one iron ion. So the iron ion carries two positive charges: Fe²⁺."),
      NE("In Fe₂O₃ bringen drei Oxid-Ionen sechs negative Ladungen. Diese verteilen sich auf zwei Eisen-Ionen – jedes trägt also drei positive Ladungen: Fe³⁺.",
        "In Fe₂O₃ three oxide ions bring six negative charges. They are shared by two iron ions – so each one carries three positive charges: Fe³⁺."),
      NE("Damit man die beiden Stoffe unterscheiden kann, steht die Ladung als **römische Zahl** im Namen: Eisen(II)-oxid und Eisen(III)-oxid.",
        "To tell the two substances apart, the charge is written as a **Roman numeral** in the name: iron(II) oxide and iron(III) oxide."),
    ],
    ok: NE("Dieselben Elemente können also verschiedene Stoffe bilden. Hat das Metall-Ion eine andere Ladung, ist es ein anderer Stoff mit eigenem Namen.",
      "So the same elements can form different substances. If the metal ion has a different charge, it is a different substance with its own name."),
    visual: c => <OxidePair c={c} items={[{ Z: FE, q: 2, nC: 1, nA: 1, sample: "FeO" }, { Z: FE, q: 3, nC: 2, nA: 3, sample: "Fe2O3" }]} />,
  }),
  model({
    mode: "faded",
    say: NE("Auch Kupfer bildet zwei Oxide: rotes **Cu₂O** und schwarzes **CuO**. Das Bild zeigt sofort, ob sich die Ladungen ausgleichen.",
      "Copper also forms two oxides: red **Cu₂O** and black **CuO**. The picture shows at once whether the charges balance."),
    ask: NE("Welche Ladung hat das Kupfer-Ion im schwarzen CuO?", "What is the charge of the copper ion in black CuO?"),
    lines: [
      NE("Ein Oxid-Ion O²⁻ bringt zwei negative Ladungen.", "One oxide ion O²⁻ brings two negative charges."),
      NE("Ein einziges Kupfer-Ion gleicht sie aus.", "A single copper ion balances them."),
      NE("Das Kupfer-Ion trägt also die Ladung {?}.", "So the copper ion carries the charge {?}."),
    ],
    answer: "2+",
    why: {
      "1+": NE("Mit der Ladung 1+ bringt das Kupfer-Ion nur eine positive Ladung. Das O²⁻ hat aber zwei negative.",
        "With the charge 1+ the copper ion brings only one positive charge. But the O²⁻ has two negative ones."),
      "3+": NE("Mit der Ladung 3+ hätte das Kupfer-Ion drei positive Ladungen. Das ist eine mehr, als das O²⁻ negative hat.",
        "With the charge 3+ the copper ion would have three positive charges. That is one more than the O²⁻ has negative ones."),
    },
    tip: NE("Wie viele negative Ladungen hat das O²⁻?", "How many negative charges does the O²⁻ have?"),
    ok: NE("Im schwarzen CuO gleichen sich Cu²⁺ und O²⁻ im Verhältnis 1 : 1 aus. Der Stoff heißt deshalb Kupfer(II)-oxid.",
      "In black CuO, Cu²⁺ and O²⁻ balance in a 1 : 1 ratio. So the substance is called copper(II) oxide."),
    visual: c => <WallModel c={c} Z={CU} anion="O2-" charges={[1, 2, 3]} report="charge" given="CuO" sample="CuO" sampleAlways init={{ q: 1, nC: 1, nA: 1 }} sol={{ q: 2, nC: 1, nA: 1 }} />,
  }),
  model({
    mode: "free",
    ask: NE("Welche Ladung hat jedes Kupfer-Ion im roten Cu₂O? Stelle zuerst die Anzahlen wie in der Formel ein und wähle dann die Ladung.",
      "What is the charge of each copper ion in red Cu₂O? First set the numbers as in the formula, then choose the charge."),
    answer: "1+",
    why: {
      "≠ Anzahl": NE("In Cu₂O kommen zwei Kupfer-Ionen auf ein Oxid-Ion. Stelle zuerst diese Anzahlen ein.",
        "In Cu₂O there are two copper ions for every oxide ion. Set these numbers first."),
      "2+": NE("Die 2 in Cu₂ ist die Anzahl der Kupfer-Ionen, nicht ihre Ladung. Zwei Cu²⁺ brächten vier positive Ladungen, das O²⁻ hat nur zwei negative.",
        "The 2 in Cu₂ is the number of copper ions, not their charge. Two Cu²⁺ would bring four positive charges, but the O²⁻ has only two negative ones."),
      "3+": NE("Mit der Ladung 3+ hätten zwei Kupfer-Ionen zusammen sechs positive Ladungen. Das O²⁻ hat aber nur zwei negative.",
        "With the charge 3+, two copper ions would have six positive charges together. But the O²⁻ has only two negative ones."),
    },
    tip: NE("Stelle zuerst die Anzahlen aus der Formel ein. Überlege dann, wie sich die zwei negativen Ladungen des O²⁻ auf die Kupfer-Ionen verteilen.",
      "First set the numbers from the formula. Then think about how the two negative charges of the O²⁻ are shared among the copper ions."),
    lines: [NE("Ein O²⁻ bringt zwei negative Ladungen. Sie verteilen sich auf zwei Kupfer-Ionen – jedes trägt also eine positive Ladung.",
      "One O²⁻ brings two negative charges. They are shared by two copper ions – so each carries one positive charge.")],
    ok: NE("Jedes Kupfer-Ion im roten Cu₂O ist ein Cu⁺. Der Stoff heißt deshalb Kupfer(I)-oxid.", "Each copper ion in red Cu₂O is a Cu⁺. So the substance is called copper(I) oxide."),
    visual: c => <WallModel c={c} Z={CU} anion="O2-" charges={[1, 2, 3]} stepC stepA report="charge" given="Cu2O" sample="Cu2O" sampleAlways init={{ q: 3, nC: 1, nA: 1 }} sol={{ q: 1, nC: 2, nA: 1 }} />,
  }),
  model({
    mode: "worked",
    say: NE("Das große PSE hat 18 Spalten, die Gruppen. Gruppe 1 und 2 sind die **I. und II. Hauptgruppe**, Gruppe 13 bis 18 die **III. bis VIII. Hauptgruppe**. Dazwischen liegen die **Nebengruppen** mit den **Nebengruppenmetallen**.",
      "The large periodic table has 18 columns, the groups. Groups 1 and 2 are **main groups I and II**, groups 13 to 18 are **main groups III to VIII**. In between lie groups 3 to 12 with the **transition metals**."),
    ask: NE("Woher kennst du die Ladung eines Metall-Ions?", "Where do you get the charge of a metal ion from?"),
    lines: [
      NE("Aluminium steht in Gruppe 13, der III. Hauptgruppe. An der Hauptgruppe liest du die Ladung ab: Al³⁺.",
        "Aluminium is in group 13, main group III. You read the charge from the main group: Al³⁺."),
      NE("Eisen steht in Gruppe 8, einer Nebengruppe. Hier verrät das PSE die Ladung nicht – sie steht im Namen, wie bei Eisen(II)-chlorid FeCl₂ und Eisen(III)-chlorid FeCl₃.",
        "Iron is in group 8, among the transition metals. Here the periodic table does not give the charge. It is in the name, as in iron(II) chloride FeCl₂ and iron(III) chloride FeCl₃."),
    ],
    ok: NE("Bei Metallen der I. bis III. Hauptgruppe, etwa Natrium und Aluminium, liest du die Ladung an der Hauptgruppe ab. Bei allen anderen Metallen steht sie als römische Zahl im Namen.",
      "For metals of main groups I to III, such as sodium and aluminium, you read the charge from the main group. For all other metals it is a Roman numeral in the name."),
    visual: c => <GroupStrip c={c} metals={[11, MG, FE, CU, AL, PB]} />,
  }),
  model({
    mode: "faded",
    ask: NE("Bei welchen dieser Metalle muss die Ladung im Namen stehen?", "For which of these metals must the charge be in the name?"),
    lines: [
      NE("In Gruppe 1, 2 und 13, der I. bis III. Hauptgruppe, liest du die Ladung im PSE ab.", "In groups 1, 2 and 13, main groups I to III, the periodic table gives the charge."),
      NE("In den Nebengruppen, Gruppe 3 bis 12, steht sie im Namen.", "In groups 3 to 12, the transition metals, it is in the name."),
      NE("Eine römische Zahl bekommen also: {?}", "So these get a Roman numeral: {?}"),
    ],
    answer: "Fe Cu",
    why: pseWhy(PSE_A, [FE, CU]),
    tip: NE("Lies die Gruppennummer über der Spalte ab: Hauptgruppe oder Nebengruppe?", "Read the group number above the column: main group or transition metal?"),
    ok: NE("Eisen (Gruppe 8) und Kupfer (Gruppe 11) sind Nebengruppenmetalle. Ihre Ladung steht im Namen.",
      "Iron (group 8) and copper (group 11) are transition metals. Their charge is in the name."),
    visual: c => <PseMetals c={c} cands={PSE_A} answer={[FE, CU]} />,
  }),
  model({
    mode: "free",
    say: NE("Auch in der IV. Hauptgruppe steht ein Metall: **Blei** (Pb). Es bildet gelbes PbO mit Pb²⁺ und dunkelbraunes PbO₂ mit Pb⁴⁺, deshalb bekommt es eine römische Zahl.",
      "Main group IV also contains a metal: **lead** (Pb). It forms yellow PbO with Pb²⁺ and dark brown PbO₂ with Pb⁴⁺, so it gets a Roman numeral."),
    ask: NE("Umgekehrt: Bei welchen Metallen liest du die Ladung an der Hauptgruppe ab?", "Now the reverse: for which metals does the main group give the charge?"),
    answer: "Al K Ba",
    why: pseWhy(PSE_B, [AL, K, BA]),
    tip: NE("Welche Gruppennummern haben die I. bis III. Hauptgruppe im großen PSE?", "Which group numbers do main groups I to III have in the large periodic table?"),
    lines: [NE("Kalium bildet K⁺, Barium Ba²⁺ und Aluminium Al³⁺ – passend zur I., II. und III. Hauptgruppe.",
      "Potassium forms K⁺, barium Ba²⁺ and aluminium Al³⁺ – matching main groups I, II and III.")],
    ok: NE("Bei Eisen, Kupfer und Blei steht die Ladung dagegen als römische Zahl im Namen.", "For iron, copper and lead the charge is a Roman numeral in the name instead."),
    visual: c => <PseMetals c={c} cands={PSE_B} answer={[AL, K, BA]} bare />,
  }),
  {
    mode: "free",
    ask: NE("Warum heißt FeCl₃ Eisen(III)-chlorid, NaCl aber nur Natriumchlorid?", "Why is FeCl₃ called iron(III) chloride, but NaCl just sodium chloride?"),
    options: [
      NE("Die III zählt die Eisen-Ionen.", "The III counts the iron ions."),
      NE("Eisen ist schwerer als Natrium.", "Iron is heavier than sodium."),
      NE("Eisen bildet verschiedene Ionen.", "Iron forms different ions."),
      NE("Eisen will 3 Elektronen abgeben.", "Iron wants to lose 3 electrons."),
    ],
    answer: NE("Eisen bildet verschiedene Ionen.", "Iron forms different ions."),
    why: {
      [NE("Die III zählt die Eisen-Ionen.", "The III counts the iron ions.")]: NE("Die III gibt die Ladung des Eisen-Ions an, nicht die Anzahl. In FeCl₃ steckt nur ein Eisen-Ion.",
        "The III gives the charge of the iron ion, not a number of particles. FeCl₃ contains only one iron ion."),
      [NE("Eisen ist schwerer als Natrium.", "Iron is heavier than sodium.")]: NE("Die Masse spielt für den Namen keine Rolle. Die römische Zahl gibt die Ladung des Metall-Ions an.",
        "Mass plays no part in the name. The Roman numeral gives the charge of the metal ion."),
      [NE("Eisen will 3 Elektronen abgeben.", "Iron wants to lose 3 electrons.")]: NE("Das klingt, als hätte Eisen einen eigenen Willen. Entscheidend ist: Eisen bildet Fe²⁺ und Fe³⁺, und der Name zeigt, welches Ion im Stoff steckt.",
        "That sounds as if iron had a will of its own. What matters is that iron forms Fe²⁺ and Fe³⁺, and the name shows which ion is in the substance."),
    },
    ok: NE("Bei Natrium verrät schon die I. Hauptgruppe die Ladung: Na⁺. Eisen bildet Fe²⁺ und Fe³⁺ – die römische Zahl sagt, welches der beiden Ionen im Stoff steckt.",
      "For sodium, main group I already gives the charge: Na⁺. Iron forms Fe²⁺ and Fe³⁺ – the Roman numeral says which of the two ions is in the substance."),
  },

  // ── 2. Name → Formel ──
  model({
    mode: "worked", part: NE("Vom Namen zur Formel", "From name to formula"),
    say: NE("Die römische Zahl in Klammern gibt die Ladung des Metall-Ions an. Eisen(II) steht für Fe²⁺, Eisen(III) für Fe³⁺.",
      "The Roman numeral in brackets gives the charge of the metal ion. Iron(II) stands for Fe²⁺, iron(III) for Fe³⁺."),
    ask: NE("Welche Formel hat Eisen(III)-chlorid?", "What is the formula of iron(III) chloride?"),
    lines: [
      NE("Das Eisen(III)-Ion ist Fe³⁺, das Chlorid-Ion ist Cl⁻.", "The iron(III) ion is Fe³⁺, the chloride ion is Cl⁻."),
      NE("Ein Fe³⁺ trägt drei positive Ladungen. Erst drei Cl⁻ gleichen sie aus.", "One Fe³⁺ carries three positive charges. It takes three Cl⁻ to balance them."),
      NE("So entsteht die Formel **FeCl₃**. Die III im Namen ist die Ladung, keine Anzahl.", "This gives the formula **FeCl₃**. The III in the name is the charge, not a number of particles."),
    ],
    ok: NE("Die römische Zahl verrät die Ladung des Metall-Ions. Danach gleichst du die Ladungen wie gewohnt aus.",
      "The Roman numeral tells you the charge of the metal ion. Then you balance the charges as usual."),
    visual: c => <WallModel c={c} Z={FE} anion="Cl-" charges={[2, 3]} numerals stepA report="formula" given={NE("Eisen(III)-chlorid", "Iron(III) chloride")}
      init={{ q: 3, nC: 1, nA: 3 }} sol={{ q: 3, nC: 1, nA: 3 }} />,
  }),
  model({
    mode: "faded",
    say: NE("Wählst du eine andere römische Zahl, ändert sich sofort die Ladung des Eisen-Ions im Bild.",
      "If you choose a different Roman numeral, the charge of the iron ion in the picture changes at once."),
    ask: NE("Baue Eisen(II)-chlorid.", "Build iron(II) chloride."),
    lines: [
      NE("Eisen(II) steht für Fe²⁺ mit zwei positiven Ladungen.", "Iron(II) stands for Fe²⁺ with two positive charges."),
      NE("Zwei Chlorid-Ionen bringen zusammen zwei negative Ladungen und gleichen das Fe²⁺ aus.", "Two chloride ions together bring two negative charges and balance the Fe²⁺."),
      NE("Die Formel lautet also {?}.", "So the formula is {?}."),
    ],
    answer: "FeCl₂",
    why: wallWhy(FE, "Cl-", { q: 2, nC: 1, nA: 2 }, [2, 3]),
    tip: NE("Welche Ladung steckt in (II)? Wie viele Cl⁻ braucht man, um sie auszugleichen?", "Which charge is in (II)? How many Cl⁻ do you need to balance it?"),
    ok: NE("Ein Fe²⁺ und zwei Cl⁻ gleichen sich aus. Eisen(II)-chlorid hat also die Formel FeCl₂.", "One Fe²⁺ and two Cl⁻ balance each other. So iron(II) chloride has the formula FeCl₂."),
    visual: c => <WallModel c={c} Z={FE} anion="Cl-" charges={[2, 3]} numerals stepA report="formula" given={NE("Eisen(II)-chlorid", "Iron(II) chloride")}
      init={{ q: 3, nC: 1, nA: 1 }} sol={{ q: 2, nC: 1, nA: 2 }} />,
  }),
  model({
    mode: "free",
    ask: NE("Baue Kupfer(I)-oxid.", "Build copper(I) oxide."),
    answer: "Cu₂O",
    why: wallWhy(CU, "O2-", { q: 1, nC: 2, nA: 1 }, [1, 2]),
    tip: NE("(I) steht für die Ladung 1+. Wie viele Cu⁺ gleichen ein O²⁻ aus?", "(I) stands for the charge 1+. How many Cu⁺ balance one O²⁻?"),
    lines: [NE("Ein Cu⁺ hat nur eine positive Ladung, ein O²⁻ aber zwei negative. Darum braucht man zwei Cu⁺: Cu₂O, ein rotes Pulver.",
      "One Cu⁺ has only one positive charge, but one O²⁻ has two negative ones. So you need two Cu⁺: Cu₂O, a red powder.")],
    ok: NE("Zwei Cu⁺ gleichen ein O²⁻ aus. Kupfer(I)-oxid hat also die Formel Cu₂O.", "Two Cu⁺ balance one O²⁻. So copper(I) oxide has the formula Cu₂O."),
    visual: c => <WallModel c={c} Z={CU} anion="O2-" charges={[1, 2]} numerals stepC stepA report="formula" given={NE("Kupfer(I)-oxid", "Copper(I) oxide")} sample="Cu2O"
      init={{ q: 2, nC: 1, nA: 2 }} sol={{ q: 1, nC: 2, nA: 1 }} />,
  }),
  model({
    mode: "free",
    ask: NE("Baue Eisen(III)-oxid.", "Build iron(III) oxide."),
    answer: "Fe₂O₃",
    why: wallWhy(FE, "O2-", { q: 3, nC: 2, nA: 3 }, [2, 3]),
    tip: NE("Ein Fe³⁺ hat drei positive Ladungen, ein O²⁻ zwei negative. Bei welchen Anzahlen gleichen sich die Ladungen aus?",
      "One Fe³⁺ has three positive charges, one O²⁻ two negative ones. For which numbers do the charges balance?"),
    lines: [NE("Zwei Fe³⁺ bringen sechs positive Ladungen, drei O²⁻ sechs negative. So entsteht Fe₂O₃, rotbraun wie Rost.",
      "Two Fe³⁺ bring six positive charges, three O²⁻ six negative ones. This gives Fe₂O₃, red-brown like rust.")],
    ok: NE("Eisen(III)-oxid hat die Formel Fe₂O₃. Hier braucht man von beiden Ionen mehrere.", "Iron(III) oxide has the formula Fe₂O₃. Here you need several of both ions."),
    visual: c => <WallModel c={c} Z={FE} anion="O2-" charges={[2, 3]} numerals stepC stepA report="formula" given={NE("Eisen(III)-oxid", "Iron(III) oxide")} sample="Fe2O3"
      init={{ q: 2, nC: 1, nA: 1 }} sol={{ q: 3, nC: 2, nA: 3 }} />,
  }),
  model({
    mode: "free",
    say: NE("Auch bei Blei liest du die Ladung aus dem Namen ab.", "With lead, too, you read the charge from the name."),
    ask: NE("Baue Blei(II)-chlorid.", "Build lead(II) chloride."),
    answer: "PbCl₂",
    why: wallWhy(PB, "Cl-", { q: 2, nC: 1, nA: 2 }, [2]),
    tip: NE("Blei(II) steht für Pb²⁺. Wie viele Cl⁻ gleichen seine Ladung aus?", "Lead(II) stands for Pb²⁺. How many Cl⁻ balance its charge?"),
    lines: [NE("Ein Pb²⁺ trägt zwei positive Ladungen. Zwei Cl⁻ gleichen sie aus: PbCl₂.", "One Pb²⁺ carries two positive charges. Two Cl⁻ balance them: PbCl₂.")],
    ok: NE("Blei(II)-chlorid hat die Formel PbCl₂ – auf ein Pb²⁺ kommen zwei Cl⁻.", "Lead(II) chloride has the formula PbCl₂ – there are two Cl⁻ for every Pb²⁺."),
    visual: c => <WallModel c={c} Z={PB} anion="Cl-" stepC stepA report="formula" given={NE("Blei(II)-chlorid", "Lead(II) chloride")}
      init={{ q: 2, nC: 2, nA: 1 }} sol={{ q: 2, nC: 1, nA: 2 }} />,
  }),
  {
    mode: "free",
    ask: NE("Welche Formel hat Kupfer(II)-oxid?", "What is the formula of copper(II) oxide?"),
    options: ["Cu₂O", "CuO₂", "CuO", "Cu₂O₂"], answer: "CuO",
    why: {
      "Cu₂O": NE("Die II gibt die Ladung an, nicht die Anzahl der Kupfer-Ionen. Cu₂O ist das rote Kupfer(I)-oxid.",
        "The II gives the charge, not the number of copper ions. Cu₂O is red copper(I) oxide."),
      "CuO₂": NE("Die II gehört zum Kupfer-Ion, nicht zum Sauerstoff. Cu²⁺ und O²⁻ gleichen sich im Verhältnis 1 : 1 aus.",
        "The II belongs to the copper ion, not to oxygen. Cu²⁺ and O²⁻ balance in a 1 : 1 ratio."),
      "Cu₂O₂": NE("Das ist neutral, aber nicht das kleinste Verhältnis. 2 : 2 lässt sich zu 1 : 1 kürzen.",
        "That is neutral, but not the smallest ratio. 2 : 2 can be reduced to 1 : 1."),
    },
    ok: NE("Kupfer(II) steht für Cu²⁺. Cu²⁺ und O²⁻ haben gleich viele Ladungen, darum lautet die Formel CuO.",
      "Copper(II) stands for Cu²⁺. Cu²⁺ and O²⁻ carry the same number of charges, so the formula is CuO."),
  },

  // ── 3. Formel → Name ──
  model({
    mode: "worked", part: NE("Von der Formel zum Namen", "From formula to name"),
    say: NE("Von der Formel zum Namen gehst du rückwärts vor. Die Anionen zeigen, wie viel negative Ladung die Metall-Ionen ausgleichen.",
      "From formula to name you work backwards. The anions show how much negative charge the metal ions balance."),
    ask: NE("Welche Ladung hat das Eisen-Ion in FeCl₃?", "What is the charge of the iron ion in FeCl₃?"),
    lines: [
      NE("Drei Chlorid-Ionen Cl⁻ bringen drei negative Ladungen.", "Three chloride ions Cl⁻ bring three negative charges."),
      NE("Ein einziges Eisen-Ion gleicht sie aus. Es trägt also drei positive Ladungen: Fe³⁺.", "A single iron ion balances them. So it carries three positive charges: Fe³⁺."),
      NE("Der Name lautet deshalb Eisen(III)-chlorid.", "So the name is iron(III) chloride."),
    ],
    ok: NE("Zähle zuerst die negativen Ladungen der Anionen. Verteile sie dann auf die Metall-Ionen.", "First count the negative charges of the anions. Then share them among the metal ions."),
    visual: c => <WallModel c={c} Z={FE} anion="Cl-" charges={[1, 2, 3]} report="charge" given="FeCl3" init={{ q: 3, nC: 1, nA: 3 }} sol={{ q: 3, nC: 1, nA: 3 }} />,
  }),
  model({
    mode: "faded",
    ask: NE("Welche Ladung hat das Kupfer-Ion in CuBr₂?", "What is the charge of the copper ion in CuBr₂?"),
    lines: [
      NE("Zwei Bromid-Ionen Br⁻ bringen zwei negative Ladungen.", "Two bromide ions Br⁻ bring two negative charges."),
      NE("Ein einziges Kupfer-Ion gleicht sie aus.", "A single copper ion balances them."),
      NE("Das Kupfer-Ion trägt also die Ladung {?}.", "So the copper ion carries the charge {?}."),
    ],
    answer: "2+",
    why: {
      "1+": NE("Mit der Ladung 1+ bringt das Kupfer-Ion nur eine positive Ladung. Die zwei Br⁻ haben aber zwei negative.",
        "With the charge 1+ the copper ion brings only one positive charge. But the two Br⁻ have two negative ones."),
      "3+": NE("Mit der Ladung 3+ hätte das Kupfer-Ion drei positive Ladungen. Die zwei Br⁻ haben aber nur zwei negative.",
        "With the charge 3+ the copper ion would have three positive charges. But the two Br⁻ have only two negative ones."),
    },
    tip: NE("Wie viele negative Ladungen bringen die beiden Br⁻ zusammen?", "How many negative charges do the two Br⁻ bring together?"),
    ok: NE("In CuBr₂ steckt also Cu²⁺. Der Name lautet Kupfer(II)-bromid.", "So CuBr₂ contains Cu²⁺. Its name is copper(II) bromide."),
    visual: c => <WallModel c={c} Z={CU} anion="Br-" charges={[1, 2, 3]} report="charge" given="CuBr2" init={{ q: 1, nC: 1, nA: 2 }} sol={{ q: 2, nC: 1, nA: 2 }} />,
  }),
  model({
    mode: "free",
    ask: NE("Welche Ladung hat jedes Kupfer-Ion in Cu₂S? Stelle zuerst die Anzahlen aus der Formel ein und wähle dann die Ladung.",
      "What is the charge of each copper ion in Cu₂S? First set the numbers from the formula, then choose the charge."),
    answer: "1+",
    why: {
      "≠ Anzahl": NE("In Cu₂S kommen zwei Kupfer-Ionen auf ein Sulfid-Ion. Stelle zuerst diese Anzahlen ein.",
        "In Cu₂S there are two copper ions for every sulfide ion. Set these numbers first."),
      "2+": NE("Die 2 in Cu₂ ist die Anzahl der Kupfer-Ionen, nicht ihre Ladung. Zwei Cu²⁺ brächten vier positive Ladungen, das S²⁻ hat nur zwei negative.",
        "The 2 in Cu₂ is the number of copper ions, not their charge. Two Cu²⁺ would bring four positive charges, but the S²⁻ has only two negative ones."),
      "3+": NE("Mit der Ladung 3+ hätten zwei Kupfer-Ionen zusammen sechs positive Ladungen. Das S²⁻ hat aber nur zwei negative.",
        "With the charge 3+, two copper ions would have six positive charges together. But the S²⁻ has only two negative ones."),
    },
    tip: NE("Stelle zuerst die Anzahlen aus der Formel ein. Wie verteilen sich dann die zwei negativen Ladungen des S²⁻ auf die Kupfer-Ionen?",
      "First set the numbers from the formula. How are the two negative charges of the S²⁻ then shared among the copper ions?"),
    lines: [NE("Ein S²⁻ bringt zwei negative Ladungen. Sie verteilen sich auf zwei Kupfer-Ionen – jedes trägt also eine positive Ladung.",
      "One S²⁻ brings two negative charges. They are shared by two copper ions – so each carries one positive charge.")],
    ok: NE("Jedes Kupfer-Ion in Cu₂S ist ein Cu⁺. Der Name lautet deshalb Kupfer(I)-sulfid.", "Each copper ion in Cu₂S is a Cu⁺. So the name is copper(I) sulfide."),
    visual: c => <WallModel c={c} Z={CU} anion="S2-" charges={[1, 2, 3]} stepC stepA report="charge" given="Cu2S" init={{ q: 3, nC: 1, nA: 1 }} sol={{ q: 1, nC: 2, nA: 1 }} />,
  }),
  model({
    mode: "free",
    ask: NE("Welche Ladung hat das Eisen-Ion in FeBr₂? Stelle zuerst die Anzahlen ein und wähle dann die Ladung.",
      "What is the charge of the iron ion in FeBr₂? First set the numbers, then choose the charge."),
    answer: "2+",
    why: {
      "≠ Anzahl": NE("In FeBr₂ kommen zwei Bromid-Ionen auf ein Eisen-Ion. Stelle zuerst diese Anzahlen ein.",
        "In FeBr₂ there are two bromide ions for every iron ion. Set these numbers first."),
      "3+": NE("Mit der Ladung 3+ hätte das Eisen-Ion drei positive Ladungen. Die zwei Br⁻ bringen aber nur zwei negative.",
        "With the charge 3+ the iron ion would have three positive charges. But the two Br⁻ bring only two negative ones."),
      "1+": NE("Mit der Ladung 1+ bringt das Eisen-Ion nur eine positive Ladung. Die zwei Br⁻ bringen aber zwei negative.",
        "With the charge 1+ the iron ion brings only one positive charge. But the two Br⁻ bring two negative ones."),
    },
    tip: NE("Stelle zuerst die Anzahlen aus der Formel ein. Wie viele negative Ladungen bringen zwei Br⁻?",
      "First set the numbers from the formula. How many negative charges do two Br⁻ bring?"),
    lines: [NE("Zwei Br⁻ bringen zwei negative Ladungen. Ein einziges Eisen-Ion gleicht sie aus: Fe²⁺.", "Two Br⁻ bring two negative charges. A single iron ion balances them: Fe²⁺.")],
    ok: NE("FeBr₂ enthält also Fe²⁺ und heißt Eisen(II)-bromid.", "So FeBr₂ contains Fe²⁺ and is called iron(II) bromide."),
    visual: c => <WallModel c={c} Z={FE} anion="Br-" charges={[1, 2, 3]} stepC stepA report="charge" given="FeBr2" init={{ q: 3, nC: 1, nA: 1 }} sol={{ q: 2, nC: 1, nA: 2 }} />,
  }),
  model({
    mode: "free",
    ask: NE("Wie heißt CuCl₂? Stelle zuerst die Anzahlen ein und wähle dann die römische Zahl.", "What is CuCl₂ called? First set the numbers, then choose the Roman numeral."),
    answer: NE("Kupfer(II)-chlorid", "Copper(II) chloride"),
    why: {
      "≠ Anzahl": NE("In CuCl₂ kommen zwei Chlorid-Ionen auf ein Kupfer-Ion. Stelle zuerst diese Anzahlen ein.",
        "In CuCl₂ there are two chloride ions for every copper ion. Set these numbers first."),
      [NE("Kupfer(I)-chlorid", "Copper(I) chloride")]: NE("Kupfer(I) steht für Cu⁺ mit nur einer positiven Ladung. Die zwei Cl⁻ bringen aber zwei negative.",
        "Copper(I) stands for Cu⁺ with only one positive charge. But the two Cl⁻ bring two negative ones."),
      [NE("Kupfer(III)-chlorid", "Copper(III) chloride")]: NE("Mit (III) hätte das Kupfer-Ion drei positive Ladungen. Die zwei Cl⁻ bringen aber nur zwei negative.",
        "With (III) the copper ion would have three positive charges. But the two Cl⁻ bring only two negative ones."),
    },
    tip: NE("Stelle zuerst die Anzahlen aus der Formel ein. Wie viele negative Ladungen bringen die Cl⁻ zusammen?",
      "First set the numbers from the formula. How many negative charges do the Cl⁻ bring together?"),
    lines: [NE("Zwei Cl⁻ bringen zwei negative Ladungen. Ein Kupfer-Ion gleicht sie aus, es ist also Cu²⁺.", "Two Cl⁻ bring two negative charges. One copper ion balances them, so it is Cu²⁺.")],
    ok: NE("CuCl₂ enthält Cu²⁺ und heißt deshalb Kupfer(II)-chlorid.", "CuCl₂ contains Cu²⁺, so it is called copper(II) chloride."),
    visual: c => <WallModel c={c} Z={CU} anion="Cl-" charges={[1, 2, 3]} numerals stepC stepA report="name" given="CuCl2" init={{ q: 1, nC: 1, nA: 1 }} sol={{ q: 2, nC: 1, nA: 2 }} />,
  }),
  {
    mode: "free",
    ask: NE("Wie heißt Fe₂O₃?", "What is Fe₂O₃ called?"),
    options: [NE("Eisen(II)-oxid", "Iron(II) oxide"), NE("Eisen(III)-oxid", "Iron(III) oxide"), NE("Eisenoxid", "Iron oxide"), NE("Eisen(VI)-oxid", "Iron(VI) oxide")],
    answer: NE("Eisen(III)-oxid", "Iron(III) oxide"),
    why: {
      [NE("Eisen(II)-oxid", "Iron(II) oxide")]: NE("Die 2 in Fe₂ ist die Anzahl der Eisen-Ionen, nicht ihre Ladung. Drei O²⁻ bringen sechs negative Ladungen – das sind drei für jedes Eisen-Ion.",
        "The 2 in Fe₂ is the number of iron ions, not their charge. Three O²⁻ bring six negative charges – that is three for each iron ion."),
      [NE("Eisenoxid", "Iron oxide")]: NE("Eisen bildet zwei Oxide, FeO und Fe₂O₃. Ohne römische Zahl weiß man nicht, welches gemeint ist.",
        "Iron forms two oxides, FeO and Fe₂O₃. Without a Roman numeral you cannot tell which one is meant."),
      [NE("Eisen(VI)-oxid", "Iron(VI) oxide")]: NE("Sechs negative Ladungen bringen alle drei O²⁻ zusammen. Sie verteilen sich aber auf zwei Eisen-Ionen – jedes trägt also drei positive Ladungen.",
        "All three O²⁻ together bring six negative charges. But they are shared by two iron ions – so each one carries three positive charges."),
    },
    ok: NE("In Fe₂O₃ teilen sich zwei Eisen-Ionen sechs positive Ladungen. Jedes ist also ein Fe³⁺, und der Stoff heißt Eisen(III)-oxid.",
      "In Fe₂O₃ two iron ions share six positive charges. So each one is an Fe³⁺, and the substance is called iron(III) oxide."),
  },

  // ── 4. Alles zusammen ──
  model({
    mode: "worked", part: NE("Alles zusammen", "Putting it together"),
    say: NE("Mit **mehratomigen Ionen** geht es genauso. Braucht man mehrere davon, steht das Ion in **Klammern**.",
      "It works the same way with **polyatomic ions**. If you need several of them, the ion goes in **brackets**."),
    ask: NE("Welche Formel hat Eisen(III)-sulfat?", "What is the formula of iron(III) sulfate?"),
    lines: [
      NE("Eisen(III) steht für Fe³⁺, Sulfat ist das Ion SO₄²⁻.", "Iron(III) stands for Fe³⁺, sulfate is the ion SO₄²⁻."),
      NE("Zwei Fe³⁺ bringen sechs positive Ladungen, drei SO₄²⁻ sechs negative.", "Two Fe³⁺ bring six positive charges, three SO₄²⁻ six negative ones."),
      NE("So entsteht **Fe₂(SO₄)₃**. Die 3 hinter der Klammer gilt für das ganze Sulfat-Ion.", "This gives **Fe₂(SO₄)₃**. The 3 after the bracket applies to the whole sulfate ion."),
    ],
    ok: NE("Du liest die Ladung aus dem Namen ab und gleichst die Ladungen aus. Kommt ein mehratomiges Ion mehrmals vor, setzt du Klammern.",
      "You read the charge from the name and balance the charges. If a polyatomic ion occurs more than once, you add brackets."),
    visual: c => <WallModel c={c} Z={FE} anion="SO42-" charges={[2, 3]} numerals stepC stepA report="formula" given={NE("Eisen(III)-sulfat", "Iron(III) sulfate")}
      init={{ q: 3, nC: 2, nA: 3 }} sol={{ q: 3, nC: 2, nA: 3 }} />,
  }),
  model({
    mode: "faded",
    ask: NE("Baue Kupfer(II)-nitrat.", "Build copper(II) nitrate."),
    lines: [
      NE("Kupfer(II) steht für Cu²⁺, Nitrat ist das Ion NO₃⁻.", "Copper(II) stands for Cu²⁺, nitrate is the ion NO₃⁻."),
      NE("Ein Cu²⁺ trägt zwei positive Ladungen. Zwei NO₃⁻ gleichen sie aus.", "One Cu²⁺ carries two positive charges. Two NO₃⁻ balance them."),
      NE("Die Formel lautet also {?}.", "So the formula is {?}."),
    ],
    answer: "Cu(NO₃)₂",
    why: wallWhy(CU, "NO3-", { q: 2, nC: 1, nA: 2 }, [1, 2]),
    tip: NE("(II) steht für die Ladung 2+. Wie viele NO₃⁻ gleichen sie aus?", "(II) stands for the charge 2+. How many NO₃⁻ balance it?"),
    ok: NE("Cu(NO₃)₂ enthält zwei Nitrat-Ionen. Darum steht NO₃ in Klammern.", "Cu(NO₃)₂ contains two nitrate ions. That is why NO₃ is in brackets."),
    visual: c => <WallModel c={c} Z={CU} anion="NO3-" charges={[1, 2]} numerals stepC stepA report="formula" given={NE("Kupfer(II)-nitrat", "Copper(II) nitrate")}
      init={{ q: 2, nC: 1, nA: 1 }} sol={{ q: 2, nC: 1, nA: 2 }} />,
  }),
  model({
    mode: "free",
    ask: NE("Baue Eisen(II)-hydroxid.", "Build iron(II) hydroxide."),
    answer: "Fe(OH)₂",
    why: wallWhy(FE, "OH-", { q: 2, nC: 1, nA: 2 }, [2, 3]),
    tip: NE("Hydroxid ist das Ion OH⁻. Wie viele davon gleichen ein Fe²⁺ aus?", "Hydroxide is the ion OH⁻. How many of them balance one Fe²⁺?"),
    lines: [NE("Ein Fe²⁺ trägt zwei positive Ladungen. Zwei OH⁻ gleichen sie aus: Fe(OH)₂.", "One Fe²⁺ carries two positive charges. Two OH⁻ balance them: Fe(OH)₂.")],
    ok: NE("Die Klammer in Fe(OH)₂ zeigt: Es sind zwei ganze OH⁻-Ionen.", "The brackets in Fe(OH)₂ show that there are two whole OH⁻ ions."),
    visual: c => <WallModel c={c} Z={FE} anion="OH-" charges={[2, 3]} numerals stepC stepA report="formula" given={NE("Eisen(II)-hydroxid", "Iron(II) hydroxide")}
      init={{ q: 3, nC: 1, nA: 1 }} sol={{ q: 2, nC: 1, nA: 2 }} />,
  }),
  model({
    mode: "free",
    ask: NE("Wie heißt Fe(NO₃)₃? Stelle zuerst die Anzahlen ein und wähle dann die römische Zahl.", "What is Fe(NO₃)₃ called? First set the numbers, then choose the Roman numeral."),
    answer: NE("Eisen(III)-nitrat", "Iron(III) nitrate"),
    why: {
      "≠ Anzahl": NE("In Fe(NO₃)₃ kommen drei Nitrat-Ionen auf ein Eisen-Ion. Stelle zuerst diese Anzahlen ein.",
        "In Fe(NO₃)₃ there are three nitrate ions for every iron ion. Set these numbers first."),
      [NE("Eisen(II)-nitrat", "Iron(II) nitrate")]: NE("Eisen(II) steht für Fe²⁺ mit zwei positiven Ladungen. Die drei NO₃⁻ bringen aber drei negative.",
        "Iron(II) stands for Fe²⁺ with two positive charges. But the three NO₃⁻ bring three negative ones."),
      [NE("Eisen(I)-nitrat", "Iron(I) nitrate")]: NE("Mit (I) hätte das Eisen-Ion nur eine positive Ladung. Die drei NO₃⁻ bringen aber drei negative.",
        "With (I) the iron ion would have only one positive charge. But the three NO₃⁻ bring three negative ones."),
    },
    tip: NE("Stelle zuerst die Anzahlen aus der Formel ein. Wie viele negative Ladungen bringen drei NO₃⁻?",
      "First set the numbers from the formula. How many negative charges do three NO₃⁻ bring?"),
    lines: [NE("Drei NO₃⁻ bringen drei negative Ladungen. Ein einziges Eisen-Ion gleicht sie aus, es ist also Fe³⁺.",
      "Three NO₃⁻ bring three negative charges. A single iron ion balances them, so it is Fe³⁺.")],
    ok: NE("Fe(NO₃)₃ enthält Fe³⁺ und heißt deshalb Eisen(III)-nitrat.", "Fe(NO₃)₃ contains Fe³⁺, so it is called iron(III) nitrate."),
    visual: c => <WallModel c={c} Z={FE} anion="NO3-" charges={[1, 2, 3]} numerals stepC stepA report="name" given="Fe(NO3)3" init={{ q: 2, nC: 1, nA: 1 }} sol={{ q: 3, nC: 1, nA: 3 }} />,
  }),
  {
    mode: "free",
    ask: NE("Welche Formel hat Kupfer(II)-sulfat?", "What is the formula of copper(II) sulfate?"),
    options: ["CuSO₄", "Cu₂SO₄", "Cu(SO₄)₂", "CuS"], answer: "CuSO₄",
    why: {
      "Cu₂SO₄": NE("Die II gibt die Ladung an, nicht die Anzahl der Kupfer-Ionen. Cu²⁺ und SO₄²⁻ gleichen sich im Verhältnis 1 : 1 aus.",
        "The II gives the charge, not the number of copper ions. Cu²⁺ and SO₄²⁻ balance in a 1 : 1 ratio."),
      "Cu(SO₄)₂": NE("Zwei SO₄²⁻ brächten vier negative Ladungen. Ein Cu²⁺ hat aber nur zwei positive.",
        "Two SO₄²⁻ would bring four negative charges. But one Cu²⁺ has only two positive ones."),
      "CuS": NE("CuS wäre ein Sulfid mit dem Ion S²⁻. Sulfat ist das mehratomige Ion SO₄²⁻.", "CuS would be a sulfide with the ion S²⁻. Sulfate is the polyatomic ion SO₄²⁻."),
    },
    ok: NE("Cu²⁺ und SO₄²⁻ haben gleich viele Ladungen. Kupfer(II)-sulfat hat deshalb die Formel CuSO₄.",
      "Cu²⁺ and SO₄²⁻ carry the same number of charges. So copper(II) sulfate has the formula CuSO₄."),
  },
  {
    mode: "free",
    ask: NE("Wie heißt Fe(OH)₃?", "What is Fe(OH)₃ called?"),
    options: [NE("Eisen(I)-hydroxid", "Iron(I) hydroxide"), NE("Eisenhydroxid", "Iron hydroxide"), NE("Eisen(III)-oxid", "Iron(III) oxide"), NE("Eisen(III)-hydroxid", "Iron(III) hydroxide")],
    answer: NE("Eisen(III)-hydroxid", "Iron(III) hydroxide"),
    why: {
      [NE("Eisen(I)-hydroxid", "Iron(I) hydroxide")]: NE("Auf ein Eisen-Ion kommen drei OH⁻. Sie bringen drei negative Ladungen, das Eisen-Ion ist also Fe³⁺.",
        "There are three OH⁻ for one iron ion. They bring three negative charges, so the iron ion is Fe³⁺."),
      [NE("Eisenhydroxid", "Iron hydroxide")]: NE("Eisen bildet Fe²⁺ und Fe³⁺. Ohne römische Zahl weiß man nicht, welches Hydroxid gemeint ist.",
        "Iron forms Fe²⁺ and Fe³⁺. Without a Roman numeral you cannot tell which hydroxide is meant."),
      [NE("Eisen(III)-oxid", "Iron(III) oxide")]: NE("Die Ladung stimmt, aber OH⁻ heißt Hydroxid. Oxid ist das Ion O²⁻.", "The charge is right, but OH⁻ is called hydroxide. Oxide is the ion O²⁻."),
    },
    ok: NE("Drei OH⁻ gleichen ein Fe³⁺ aus. Fe(OH)₃ heißt deshalb Eisen(III)-hydroxid.", "Three OH⁻ balance one Fe³⁺. So Fe(OH)₃ is called iron(III) hydroxide."),
  },
];

const KNOWN_DE = ["Ion", "Kation", "Anion", "Ladung", "neutral", "Hauptgruppe", "Gruppe", "Periodensystem", "Formel", "Ionengitter", "mehratomige Ionen", "Klammern",
  "Chlorid", "Bromid", "Oxid", "Sulfid", "Hydroxid", "Nitrat", "Sulfat", "Phosphat", "Eisen", "Kupfer", "Blei", "Natrium", "Magnesium", "Aluminium", "Calcium", "Rost"];
const KNOWN_EN = ["ion", "cation", "anion", "charge", "neutral", "main group", "group", "periodic table", "formula", "ionic lattice", "polyatomic ions", "brackets",
  "chloride", "bromide", "oxide", "sulfide", "hydroxide", "nitrate", "sulfate", "phosphate", "iron", "copper", "lead", "sodium", "magnesium", "aluminium", "calcium", "rust"];

export const kapitel5 = (): Kapitel => ({
  id: "nebengruppen", nr: 5, stufe: "os",
  title: tr("Nebengruppenmetalle", "Transition metals"),
  desc: tr("Römische Zahlen im Namen verstehen und die Ladung des Metall-Ions aus der Formel bestimmen.",
    "Understand Roman numerals in names and find the charge of the metal ion from the formula."),
  def: {
    title: tr("Nebengruppenmetalle", "Transition metals"),
    known: KNOWN_DE.map((de, i) => tr(de, KNOWN_EN[i])),
    steps: steps(),
    outro: [
      tr("Erklären, warum dieselben Elemente verschiedene Stoffe bilden können, etwa schwarzes FeO und rotbraunes Fe₂O₃.",
        "Explain why the same elements can form different substances, such as black FeO and red-brown Fe₂O₃."),
      tr("Bei Metallen der I. bis III. Hauptgruppe die Ladung im PSE ablesen und bei allen anderen Metallen die **römische Zahl** im Namen nutzen.",
        "Read the charge from the periodic table for metals of main groups I to III, and use the **Roman numeral** in the name for all other metals."),
      tr("Aus dem Namen die Formel aufstellen, zum Beispiel FeCl₃ für Eisen(III)-chlorid.", "Write the formula from the name, for example FeCl₃ for iron(III) chloride."),
      tr("Aus der Formel die Ladung des Metall-Ions bestimmen und den Namen bilden, zum Beispiel Eisen(III)-oxid für Fe₂O₃.",
        "Find the charge of the metal ion from the formula and form the name, for example iron(III) oxide for Fe₂O₃."),
      tr("Das alles auch mit mehratomigen Ionen und Klammern, wie in Fe₂(SO₄)₃ und Cu(NO₃)₂.", "Do all this with polyatomic ions and brackets too, as in Fe₂(SO₄)₃ and Cu(NO₃)₂."),
    ],
  },
  explain: [
    [
      tr("Dieselben Elemente können verschiedene Stoffe bilden, wenn das Metall-Ion verschieden geladen ist.",
        "The same elements can form different substances if the metal ion carries different charges."),
      tr("Im großen PSE sind Gruppe 1 und 2 die I. und II. Hauptgruppe, Gruppe 13 bis 18 die III. bis VIII. Hauptgruppe. Dazwischen liegen die Nebengruppen.",
        "In the large periodic table, groups 1 and 2 are main groups I and II, groups 13 to 18 are main groups III to VIII. The transition metals lie in between."),
      tr("Bei Metallen der I. bis III. Hauptgruppe liest du die Ladung an der Hauptgruppe ab, zum Beispiel Mg²⁺ in der II. Hauptgruppe.",
        "For metals of main groups I to III you read the charge from the main group, for example Mg²⁺ in main group II."),
      tr("Bei allen anderen Metallen steht die Ladung als **römische Zahl** im Namen. Dazu gehören die **Nebengruppenmetalle** der Gruppen 3 bis 12 und Blei.",
        "For all other metals the charge is a **Roman numeral** in the name. This includes the **transition metals** of groups 3 to 12 and lead."),
    ],
    [
      tr("Die römische Zahl gibt die Ladung des Metall-Ions an: Kupfer(II) steht für Cu²⁺.", "The Roman numeral gives the charge of the metal ion: copper(II) stands for Cu²⁺."),
      tr("Dann gleichst du die Ladungen wie gewohnt aus. Für Kupfer(II)-fluorid ergeben ein Cu²⁺ und zwei F⁻ die Formel CuF₂.",
        "Then you balance the charges as usual. For copper(II) fluoride, one Cu²⁺ and two F⁻ give the formula CuF₂."),
      tr("Die römische Zahl ist eine **Ladung**, keine Anzahl.", "The Roman numeral is a **charge**, not a number of particles."),
    ],
    [
      tr("Rückwärts zählst du zuerst die negativen Ladungen der Anionen. In FeF₃ bringen drei F⁻ drei negative Ladungen.",
        "Working backwards, you first count the negative charges of the anions. In FeF₃ three F⁻ bring three negative charges."),
      tr("Dann verteilst du sie auf die Metall-Ionen. Ein Eisen-Ion gleicht alle drei aus, es ist also Fe³⁺: Eisen(III)-fluorid.",
        "Then you share them among the metal ions. One iron ion balances all three, so it is Fe³⁺: iron(III) fluoride."),
      tr("Eine tiefgestellte Zahl am Metall gibt die **Anzahl** an, nicht die Ladung.", "A subscript on the metal gives the **number** of ions, not the charge."),
    ],
    [
      tr("Ein mehratomiges Ion bleibt immer zusammen. Kommt es mehrmals vor, steht es in **Klammern**, zum Beispiel in Cu(OH)₂.",
        "A polyatomic ion always stays together. If it occurs more than once, it goes in **brackets**, for example in Cu(OH)₂."),
      tr("Vom Namen zur Formel liest du die Ladung an der römischen Zahl ab und gleichst aus. Eisen(II)-sulfat ist FeSO₄.",
        "From name to formula, you read the charge from the Roman numeral and balance. Iron(II) sulfate is FeSO₄."),
      tr("Von der Formel zum Namen zählst du die Ladungen der Anionen und verteilst sie auf die Metall-Ionen. Die Ladung kommt als römische Zahl in den Namen.",
        "From formula to name, you count the charges of the anions and share them among the metal ions. The charge goes into the name as a Roman numeral."),
    ],
  ],
});
