// Fehlvorstellungen (Stolpersteine) zur Elektronenpaarbindung – Schlüssel für diagnostische Distraktoren und Fallen im Baufeld.
// Die Rückmeldungstexte stehen bei den Aufgaben (mit den konkreten Molekülen); hier nur der Name für Landkarte und Auswertung.
import { tr } from "@lern/i18n";

const MISS_DE: Record<string, string> = {
  "bindungen-valenz": "Anzahl Bindungen = Außenelektronen",
  "bindungen-fehlend-verzaehlt": "Ungepaarte Elektronen verzählt",
  "h-oktett": "Auch um H 8 Elektronen gezählt",
  "nur-valenz-gezaehlt": "Nur eigene Außenelektronen gezählt (Bindungspartner vergessen)",
  "nur-bindungen-gezaehlt": "Nur bindende Elektronen gezählt (freie vergessen)",
  "valenz-als-paare": "Alle Außenelektronen als freie Paare gezählt",
  "bindungen-statt-paare": "Bindungen statt freie Paare gezählt",
  "elektronen-statt-paare": "Elektronen statt Paare gezählt",
  "mehrfachbindung-uebersehen": "Mehrfachbindung übersehen",
  "oktett-ueberschritten": "Mehr Paare als Elektronen erlauben (über das Oktett)",
  "atomzahl-falsch": "Falsche Anzahl Atome (Formel nicht gelesen)",
  "oktett-offen": "Molekül abgegeben, obwohl ein Oktett offen ist",
  "freie-paare-ignoriert": "Freie Elektronenpaare bei der Form ignoriert",
  "elektronen-statt-atome": "Anordnung der Elektronenpaare mit der Molekülform verwechselt",
  "aussen-paare-gezaehlt": "Freie Paare der Außenatome mitgezählt",
  "mehrfachbindung-doppelt-gezaehlt": "Mehrfachbindung als mehrere Bereiche gezählt",
  "stauchung-ignoriert": "Freie Paare drücken stärker – Winkel kleiner als 109,5° übersehen",
  "atom-statt-molekuel": "Element-Molekül als einzelnes Atom geschrieben (O statt O₂)",
  "element-statt-molekuel": "Name eines Bestandteils statt des Moleküls",
  "name-verwechselt": "Name eines ähnlichen Moleküls (Atome nicht genau gezählt)",
  "wuerfel-statt-tetraeder": "Winkel wie in der Zeichnung (90°) statt räumlich",
  "polare-bindung-polares-molekuel": "Polare Bindung = polares Molekül (Symmetrie übersehen)",
  "form-uebersehen": "Gewinkelten/pyramidalen Bau übersehen",
  "partner-ungleich": "Verschiedene Bindungspartner übersehen (Form allein für symmetrisch gehalten)",
  "en-uebersehen": "Elektronegativitäts-Unterschied übersehen",
  "gleiche-en-polar": "Bindung zwischen gleichen Atomen für polar gehalten",
  "ionisch-statt-polar": "Polare Bindung für Ionenbindung gehalten",
  "en-statt-differenz": "Höchste Elektronegativität statt größter Differenz",
};
const MISS_EN: Record<string, string> = {
  "bindungen-valenz": "Number of bonds = outer electrons",
  "bindungen-fehlend-verzaehlt": "Unpaired electrons miscounted",
  "h-oktett": "Counted 8 electrons around H too",
  "nur-valenz-gezaehlt": "Only own outer electrons counted (bonding partner forgotten)",
  "nur-bindungen-gezaehlt": "Only bonding electrons counted (lone pairs forgotten)",
  "valenz-als-paare": "All outer electrons counted as lone pairs",
  "bindungen-statt-paare": "Bonds counted instead of lone pairs",
  "elektronen-statt-paare": "Electrons counted instead of pairs",
  "mehrfachbindung-uebersehen": "Multiple bond overlooked",
  "oktett-ueberschritten": "More pairs than electrons allow (beyond the octet)",
  "atomzahl-falsch": "Wrong number of atoms (formula not read)",
  "oktett-offen": "Molecule submitted with an octet still open",
  "freie-paare-ignoriert": "Lone pairs ignored for the shape",
  "elektronen-statt-atome": "Arrangement of electron pairs confused with molecular shape",
  "aussen-paare-gezaehlt": "Lone pairs of the outer atoms counted",
  "mehrfachbindung-doppelt-gezaehlt": "Multiple bond counted as several regions",
  "stauchung-ignoriert": "Lone pairs push harder – angle below 109.5° overlooked",
  "atom-statt-molekuel": "Element molecule written as a single atom (O instead of O₂)",
  "element-statt-molekuel": "Name of a component instead of the molecule",
  "name-verwechselt": "Name of a similar molecule (atoms not counted carefully)",
  "wuerfel-statt-tetraeder": "Angle as in the drawing (90°) instead of in space",
  "polare-bindung-polares-molekuel": "Polar bond = polar molecule (symmetry overlooked)",
  "form-uebersehen": "Bent/pyramidal shape overlooked",
  "partner-ungleich": "Different bonding partners overlooked (shape alone taken as symmetrical)",
  "en-uebersehen": "Electronegativity difference overlooked",
  "gleiche-en-polar": "Bond between identical atoms taken as polar",
  "ionisch-statt-polar": "Polar bond taken as an ionic bond",
  "en-statt-differenz": "Highest electronegativity instead of largest difference",
};
export const MISS = tr(MISS_DE, MISS_EN);
