// Übungsaufgaben: je Stufe drei Schwierigkeiten mit je 10 festen Gleichungen, alle nur aus Molekülen
// (damit nach dem Lösen der Ablauf als Animation gezeigt werden kann). Zu jeder Gleichung ein eigener Hinweis,
// der den Weg zeigt, aber keine Zahl vor einem Stoff verrät.

import { tr } from "@lern/i18n";
import type { Stufe } from "../store.ts";

export type Lvl = "einfach" | "mittel" | "schwer";
export const LVLS: Lvl[] = ["einfach", "mittel", "schwer"];
export const LVL_NAMES: Record<Lvl, string> = tr(
  { einfach: "Einfach", mittel: "Mittel", schwer: "Schwer" },
  { einfach: "Easy", mittel: "Medium", schwer: "Hard" });

export const EXERCISES: Record<Stufe, Record<Lvl, string[]>> = {
  us: {
    einfach: ["hf", "hbr", "hi", "ch4-syn", "n2h4-o2", "no-syn", "cs2", "boudouard", "n2h4-zerfall", "methanol-syn"],
    mittel: ["co-o2", "ozon", "no-h2", "wasser", "h2o2", "nh3-zerfall", "pcl3", "co-syn", "cs2-o2", "p4o10"],
    schwer: ["ethen", "methan-co", "pentan", "zellatmung", "h2s", "methanol", "ethan", "ethin", "nh3-o2", "butan"],
  },
  os: {
    einfach: ["kontakt", "no2", "ch2cl2", "chcl3", "ccl4-ch4", "ethin-h2", "essigsaeure", "hi-zerfall", "h2s-s", "formaldehyd"],
    mittel: ["ph3-zerfall", "h3po4", "harnstoff-syn", "harnstoff", "essig-o2", "ethanal", "ameisen-o2", "aceton", "no2-h2o", "zucker-gaerung"],
    schwer: ["zucker-o2", "ph3-o2", "nh3-no2", "harnstoff-o2", "claus", "benzol", "hcn", "glycin", "dodecan", "h2s-cl2"],
  },
};

export const HINTS_DE: Record<string, string> = {
  // Level I · einfach
  "n2h4-o2": "Vergleiche die H-Atome: N₂H₄ links, H₂O rechts. Prüfe danach N und O.",
  hf: "Vergleiche die F-Atome: F₂ links, HF rechts. Prüfe danach H.",
  hbr: "Vergleiche die Br-Atome: Br₂ links, HBr rechts. Prüfe danach H.",
  hi: "Vergleiche die I-Atome: I₂ links, HI rechts. Prüfe danach H.",
  "ch4-syn": "Vergleiche die H-Atome: H₂ links, CH₄ rechts. Prüfe danach C.",
  "no-syn": "Vergleiche die N-Atome: N₂ links, NO rechts. Prüfe danach O.",
  cs2: "Vergleiche die S-Atome: S links, CS₂ rechts. Prüfe danach C.",
  boudouard: "Vergleiche die C-Atome: CO₂ und C links, CO rechts. Prüfe danach O.",
  "n2h4-zerfall": "Vergleiche die H-Atome: N₂H₄ links, H₂ rechts. Prüfe danach N.",
  "methanol-syn": "Vergleiche die H-Atome: H₂ links, CH₃OH rechts. Prüfe danach C und O.",
  // Level I · mittel
  "co-o2": "Beginne mit C: Vergleiche CO und CO₂. Gleiche danach O mit O₂ aus.",
  ozon: "Vergleiche die O-Atome: O₃ links, O₂ rechts. Suche die kleinste Zahl O-Atome, die in beide passt.",
  "no-h2": "Beginne mit N: Vergleiche NO und N₂. Dann O, zuletzt H.",
  wasser: "Beginne mit O: Vergleiche die O-Atome im H₂O und im O₂. Prüfe danach H.",
  h2o2: "Beginne mit H: Vergleiche die H-Atome in H₂O₂ und H₂O. Gleiche zuletzt O mit O₂ aus.",
  "nh3-zerfall": "Beginne mit N: Vergleiche NH₃ und N₂. Verteile danach die H-Atome auf H₂.",
  pcl3: "Beginne mit P: Vergleiche die P-Atome in P₄ und PCl₃. Gleiche danach Cl mit Cl₂ aus.",
  "co-syn": "Beginne mit O: Vergleiche die O-Atome im O₂ und im CO. Prüfe danach C.",
  "cs2-o2": "Verteile zuerst C und S: S steht rechts nur im SO₂. O₂ kommt zuletzt.",
  p4o10: "Beginne mit P: Vergleiche P₄ und P₄O₁₀. Gleiche danach O mit O₂ aus.",
  // Level I · schwer
  ethen: "C₂H₄: zuerst C, dann H. O₂ kommt zuletzt – zähle dafür alle O-Atome rechts.",
  "methan-co": "Zuerst C, dann H, O₂ zuletzt. Eine halbe Zahl heißt: alles verdoppeln.",
  pentan: "C₅H₁₂: zuerst C, dann H. O₂ kommt zuletzt – zähle dafür alle O-Atome rechts.",
  zellatmung: "Beginne mit C: Zähle die C-Atome im Traubenzucker. Zähle beim O auch die O-Atome im Zucker mit.",
  h2s: "S geht ins SO₂, H ins H₂O. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  methanol: "CH₃OH bringt selbst O mit – zähle es links mit. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  ethan: "C₂H₆: zuerst C, dann H, O₂ zuletzt. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  ethin: "Zuerst C, dann H, O₂ zuletzt. Eine halbe Zahl heißt: alles verdoppeln.",
  "nh3-o2": "N geht ins N₂, H ins H₂O. N₂ braucht eine gerade Zahl N-Atome.",
  butan: "Gleiche zuerst C und H aus. Ist die O-Zahl rechts ungerade, verdopple alle Zahlen.",
  // Level II · einfach
  kontakt: "Beginne mit S: Vergleiche SO₂ und SO₃. Gleiche danach O mit O₂ aus.",
  no2: "Beginne mit N: Vergleiche NO und NO₂. Gleiche danach O mit O₂ aus.",
  ch2cl2: "Vergleiche die H-Atome im CH₄ und im CH₂Cl₂. Wohin gehen die übrigen H? Gleiche zuletzt Cl mit Cl₂ aus.",
  chcl3: "Vergleiche die H-Atome im CH₄ und im CHCl₃. Wohin gehen die übrigen H? Gleiche zuletzt Cl mit Cl₂ aus.",
  "ccl4-ch4": "Verfolge die H-Atome des Methans: Wo stehen sie rechts? Gleiche zuletzt Cl mit Cl₂ aus.",
  "ethin-h2": "Vergleiche die H-Atome: C₂H₂ und H₂ links, C₂H₆ rechts.",
  essigsaeure: "Beginne mit C: Vergleiche CH₃CHO und CH₃COOH. Gleiche danach O mit O₂ aus.",
  "hi-zerfall": "Beginne mit H: Vergleiche die H-Atome im HI und im H₂. Prüfe danach I.",
  "h2s-s": "S bleibt als Schwefel übrig, H geht ins Wasser. Beginne mit O: Vergleiche O₂ und H₂O.",
  formaldehyd: "Beginne mit C: Vergleiche CH₃OH und CH₂O. Die übrigen H gehen ins H₂O, O₂ kommt zuletzt.",
  // Level II · mittel
  "ph3-zerfall": "Beginne mit P: Vergleiche PH₃ und P₄. Prüfe danach H.",
  h3po4: "Beginne mit P: Vergleiche die P-Atome im P₄O₁₀ und im H₃PO₄. Gleiche danach H aus, prüfe zuletzt O.",
  "harnstoff-syn": "Beginne mit N: Vergleiche die N-Atome im NH₃ und im CO(NH₂)₂. Prüfe danach H und O.",
  harnstoff: "In CO(NH₂)₂ gilt die 2 hinter der Klammer für N und H. Beginne mit N.",
  "essig-o2": "Zähle C, H und O im CH₃COOH. Zuerst C, dann H, O₂ zuletzt.",
  "ameisen-o2": "HCOOH bringt selbst O mit – zähle es links mit. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  aceton: "Zähle C, H und O im CH₃COCH₃. Zuerst C, dann H, O₂ zuletzt.",
  ethanal: "Beginne mit C: Vergleiche C₂H₅OH und CH₃CHO. Die übrigen H gehen ins H₂O, O₂ kommt zuletzt.",
  "no2-h2o": "N steht rechts zweimal: im HNO₃ und im NO. Beginne mit H, dann N, prüfe zuletzt O.",
  "zucker-gaerung": "Beginne mit C: Die C-Atome des Zuckers verteilen sich auf Ethanol und CO₂. Wasser liefert fehlende H.",
  // Level II · schwer
  "zucker-o2": "C₁₂H₂₂O₁₁ bringt selbst O mit. Zieh es ab, bevor du O₂ bestimmst.",
  "ph3-o2": "Beginne mit P: Vergleiche PH₃ und P₄O₁₀. Dann H, O₂ zuletzt.",
  "nh3-no2": "N geht ins NO₂, H ins H₂O. Wähle NH₃ so, dass H₂O eine ganze Zahl bekommt.",
  "harnstoff-o2": "Zähle C, N, H und O im Harnstoff CO(NH₂)₂. Zuerst C, N und H, O₂ zuletzt.",
  claus: "Gleiche zuerst O über H₂O aus, dann H. Schwefel S kommt zuletzt.",
  benzol: "C₆H₆: zuerst C, dann H, O₂ zuletzt. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  hcn: "Beginne mit H und N: Vergleiche HCN mit H₂O und N₂. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  glycin: "Zähle C, H, N und O im Glycin. N₂ braucht eine gerade Zahl N-Atome, O₂ kommt zuletzt.",
  dodecan: "C₁₂H₂₆: zuerst C, dann H, O₂ zuletzt. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  "h2s-cl2": "S geht ins H₂SO₄, O kommt nur aus H₂O, Cl nur aus Cl₂. Zuerst S und O, dann Cl.",
};

export const HINTS_EN: Record<string, string> = {
  "n2h4-o2": "Compare the H atoms: N₂H₄ on the left, H₂O on the right. Then check N and O.",
  hf: "Compare the F atoms: F₂ on the left, HF on the right. Then check H.",
  hbr: "Compare the Br atoms: Br₂ on the left, HBr on the right. Then check H.",
  hi: "Compare the I atoms: I₂ on the left, HI on the right. Then check H.",
  "ch4-syn": "Compare the H atoms: H₂ on the left, CH₄ on the right. Then check C.",
  "no-syn": "Compare the N atoms: N₂ on the left, NO on the right. Then check O.",
  cs2: "Compare the S atoms: S on the left, CS₂ on the right. Then check C.",
  boudouard: "Compare the C atoms: CO₂ and C on the left, CO on the right. Then check O.",
  "n2h4-zerfall": "Compare the H atoms: N₂H₄ on the left, H₂ on the right. Then check N.",
  "methanol-syn": "Compare the H atoms: H₂ on the left, CH₃OH on the right. Then check C and O.",
  "co-o2": "Start with C: compare CO and CO₂. Then balance O with O₂.",
  ozon: "Compare the O atoms: O₃ on the left, O₂ on the right. Find the smallest number of O atoms that fits both.",
  "no-h2": "Start with N: compare NO and N₂. Then O, H last.",
  wasser: "Start with O: compare the O atoms in H₂O and in O₂. Then check H.",
  h2o2: "Start with H: compare the H atoms in H₂O₂ and H₂O. Balance O with O₂ last.",
  "nh3-zerfall": "Start with N: compare NH₃ and N₂. Then share out the H atoms to H₂.",
  pcl3: "Start with P: compare the P atoms in P₄ and PCl₃. Then balance Cl with Cl₂.",
  "co-syn": "Start with O: compare the O atoms in O₂ and in CO. Then check C.",
  "cs2-o2": "Share out C and S first: S only appears in SO₂ on the right. O₂ comes last.",
  p4o10: "Start with P: compare P₄ and P₄O₁₀. Then balance O with O₂.",
  ethen: "C₂H₄: C first, then H. O₂ comes last – count all O atoms on the right for it.",
  "methan-co": "C first, then H, O₂ last. A half number means: double everything.",
  pentan: "C₅H₁₂: C first, then H. O₂ comes last – count all O atoms on the right for it.",
  zellatmung: "Start with C: count the C atoms in the glucose. When counting O, include the O atoms in the sugar.",
  h2s: "S goes into SO₂, H into H₂O. If you would need half an O₂, double all numbers.",
  methanol: "CH₃OH brings O of its own – count it on the left. If you would need half an O₂, double all numbers.",
  ethan: "C₂H₆: C first, then H, O₂ last. If you would need half an O₂, double all numbers.",
  ethin: "C first, then H, O₂ last. A half number means: double everything.",
  "nh3-o2": "N goes into N₂, H into H₂O. N₂ needs an even number of N atoms.",
  butan: "Balance C and H first. If the O count on the right is odd, double all numbers.",
  kontakt: "Start with S: compare SO₂ and SO₃. Then balance O with O₂.",
  no2: "Start with N: compare NO and NO₂. Then balance O with O₂.",
  ch2cl2: "Compare the H atoms in CH₄ and in CH₂Cl₂. Where do the other H go? Balance Cl with Cl₂ last.",
  chcl3: "Compare the H atoms in CH₄ and in CHCl₃. Where do the other H go? Balance Cl with Cl₂ last.",
  "ccl4-ch4": "Follow the H atoms of methane: where are they on the right? Balance Cl with Cl₂ last.",
  "ethin-h2": "Compare the H atoms: C₂H₂ and H₂ on the left, C₂H₆ on the right.",
  essigsaeure: "Start with C: compare CH₃CHO and CH₃COOH. Then balance O with O₂.",
  "hi-zerfall": "Start with H: compare the H atoms in HI and in H₂. Then check I.",
  "h2s-s": "S is left over as sulfur, H goes into water. Start with O: compare O₂ and H₂O.",
  formaldehyd: "Start with C: compare CH₃OH and CH₂O. The other H go into H₂O, O₂ comes last.",
  "ph3-zerfall": "Start with P: compare PH₃ and P₄. Then check H.",
  h3po4: "Start with P: compare the P atoms in P₄O₁₀ and in H₃PO₄. Then balance H and check O last.",
  "harnstoff-syn": "Start with N: compare the N atoms in NH₃ and in CO(NH₂)₂. Then check H and O.",
  harnstoff: "In CO(NH₂)₂ the 2 after the bracket applies to N and H. Start with N.",
  "essig-o2": "Count C, H and O in CH₃COOH. C first, then H, O₂ last.",
  "ameisen-o2": "HCOOH brings O of its own – count it on the left. If you would need half an O₂, double all numbers.",
  aceton: "Count C, H and O in CH₃COCH₃. C first, then H, O₂ last.",
  ethanal: "Start with C: compare C₂H₅OH and CH₃CHO. The other H go into H₂O, O₂ comes last.",
  "no2-h2o": "N appears twice on the right: in HNO₃ and in NO. Start with H, then N, check O last.",
  "zucker-gaerung": "Start with C: the C atoms of the sugar are shared between ethanol and CO₂. Water supplies missing H.",
  "zucker-o2": "C₁₂H₂₂O₁₁ brings O of its own. Subtract it before you set O₂.",
  "ph3-o2": "Start with P: compare PH₃ and P₄O₁₀. Then H, O₂ last.",
  "nh3-no2": "N goes into NO₂, H into H₂O. Choose NH₃ so that H₂O gets a whole number.",
  "harnstoff-o2": "Count C, N, H and O in urea CO(NH₂)₂. C, N and H first, O₂ last.",
  claus: "Balance O first using H₂O, then H. Sulfur S comes last.",
  benzol: "C₆H₆: C first, then H, O₂ last. If you would need half an O₂, double all numbers.",
  hcn: "Start with H and N: compare HCN with H₂O and N₂. If you would need half an O₂, double all numbers.",
  glycin: "Count C, H, N and O in glycine. N₂ needs an even number of N atoms, O₂ comes last.",
  dodecan: "C₁₂H₂₆: C first, then H, O₂ last. If you would need half an O₂, double all numbers.",
  "h2s-cl2": "S goes into H₂SO₄, O comes only from H₂O, Cl only from Cl₂. S and O first, then Cl.",
};

export const HINTS: Record<string, string> = tr(HINTS_DE, HINTS_EN);
