// Übungsaufgaben: je Stufe drei Schwierigkeiten mit je 10 festen Gleichungen, alle nur aus Molekülen
// (damit nach dem Lösen der Ablauf als Animation gezeigt werden kann). Zu jeder Gleichung ein eigener Hinweis,
// der den Weg zeigt, aber keine Zahl vor einem Stoff verrät.

import { tr } from "@lern/i18n";
import type { Stufe } from "../store.ts";

export type Lvl = "einfach" | "mittel" | "schwer";
export const LVLS: Lvl[] = ["einfach", "mittel", "schwer"];
export const LVL_NAMES: Record<Lvl, string> = tr(
  { einfach: "Einfach", mittel: "Mittel", schwer: "Schwer" },
  { einfach: "Easy", mittel: "Medium", schwer: "Hard" });

export const EXERCISES: Record<Stufe, Record<Lvl, string[]>> = {
  us: {
    einfach: ["hf", "hbr", "hi", "ch4-syn", "co2", "no-syn", "cs2", "boudouard", "n2h4-zerfall", "methanol-syn"],
    mittel: ["co-o2", "ozon", "no-h2", "wasser", "h2o2", "nh3-zerfall", "pcl3", "co-syn", "cs2-o2", "p2o5"],
    schwer: ["ethen", "ethanol", "pentan", "zellatmung", "h2s", "methanol", "ethan", "ethin", "nh3-o2", "butan"],
  },
  os: {
    einfach: ["kontakt", "no2", "ch2cl2", "chcl3", "ccl4-ch4", "ethin-h2", "essigsaeure", "hi-zerfall", "h2s-s", "formaldehyd"],
    mittel: ["p4", "h3po4", "harnstoff-syn", "harnstoff", "essig-o2", "ethanal", "ameisen-o2", "aceton", "no2-h2o", "zucker-gaerung"],
    schwer: ["zucker-o2", "ph3", "nh3-no2", "harnstoff-o2", "claus", "benzol", "hcn", "glycin", "dodecan", "h2s-cl2"],
  },
};

export const HINTS_DE: Record<string, string> = {
  // Level I · einfach
  co2: "Zähle C und O auf beiden Seiten. Ändere eine Zahl nur, wenn links und rechts verschieden viele Atome stehen.",
  hf: "Vergleiche die F-Atome: F₂ links, HF rechts. Prüfe danach H.",
  hbr: "Vergleiche die Br-Atome: Br₂ links, HBr rechts. Prüfe danach H.",
  hi: "Vergleiche die I-Atome: I₂ links, HI rechts.",
  "ch4-syn": "CH₄ hat 4 H-Atome. Jedes H₂ liefert 2 davon.",
  "no-syn": "Vergleiche die N-Atome: N₂ links, NO rechts. Prüfe danach O.",
  cs2: "Zähle die S-Atome im CS₂. Links steht Schwefel als einzelnes Atom S.",
  boudouard: "Zähle die C-Atome links im CO₂ und in der Kohle. Prüfe danach O.",
  "n2h4-zerfall": "N₂H₄ hat 4 H-Atome. Jedes H₂ nimmt 2 davon auf.",
  "methanol-syn": "CH₃OH hat 4 H-Atome. Jedes H₂ liefert 2 davon.",
  // Level I · mittel
  "co-o2": "Beginne mit C: CO und CO₂ haben je ein C. Gleiche danach O mit O₂ aus.",
  ozon: "O₃ links, O₂ rechts. Suche die kleinste Zahl O-Atome, die durch 3 und durch 2 teilbar ist.",
  "no-h2": "Beginne mit N: Vergleiche NO und N₂. Dann O, zuletzt H.",
  wasser: "Beginne mit O: Vergleiche die O-Atome im H₂O und im O₂. Prüfe danach H.",
  h2o2: "Beginne mit H: Vergleiche die H-Atome in H₂O₂ und H₂O. Gleiche zuletzt O mit O₂ aus.",
  "nh3-zerfall": "Beginne mit N: Vergleiche NH₃ und N₂. Verteile danach die H-Atome auf H₂.",
  pcl3: "Beginne mit P: Vergleiche die P-Atome in P₄ und PCl₃. Gleiche danach Cl mit Cl₂ aus.",
  "co-syn": "Beginne mit O: Vergleiche die O-Atome im O₂ und im CO. Prüfe danach C.",
  "cs2-o2": "Verteile zuerst C und S: S steht rechts nur im SO₂. O₂ kommt zuletzt.",
  p2o5: "P₂O₅ hat 5 O-Atome. O₂ liefert immer eine gerade Zahl. Wie wird die O-Zahl rechts gerade?",
  // Level I · schwer
  ethen: "C₂H₄: zuerst C, dann H. O₂ kommt zuletzt – zähle dafür alle O-Atome rechts.",
  ethanol: "C₂H₅OH hat 6 H-Atome und selbst ein O-Atom. Zähle dieses O links mit.",
  pentan: "C₅H₁₂: zuerst C, dann H. O₂ kommt zuletzt – zähle dafür alle O-Atome rechts.",
  zellatmung: "Beginne mit C: Zähle die C-Atome im Traubenzucker. Zähle beim O auch die O-Atome im Zucker mit.",
  h2s: "S geht ins SO₂, H ins H₂O. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  methanol: "CH₃OH hat selbst ein O-Atom. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  ethan: "C₂H₆: zuerst C, dann H, O₂ zuletzt. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  ethin: "C₂H₂ hat nur 2 H-Atome. Zuerst C und H, O₂ zuletzt. Eine halbe Zahl heißt: alles verdoppeln.",
  "nh3-o2": "N geht ins N₂, H ins H₂O. N₂ braucht eine gerade Zahl N-Atome.",
  butan: "Gleiche zuerst C und H aus. Ist die O-Zahl rechts ungerade, verdopple C₄H₁₀.",
  // Level II · einfach
  kontakt: "Jedes SO₃ hat ein O-Atom mehr als SO₂. O₂ liefert 2 O-Atome.",
  no2: "Jedes NO₂ hat ein O-Atom mehr als NO. O₂ liefert 2 O-Atome.",
  ch2cl2: "Jedes Cl₂ tauscht ein H aus: ein Cl geht ans C, eins ins HCl. Wie viele H werden getauscht?",
  chcl3: "Jedes Cl am C ersetzt ein H. Wohin geht dieses H? Gleiche zuletzt Cl mit Cl₂ aus.",
  "ccl4-ch4": "Verfolge die H-Atome des Methans: Wo stehen sie rechts? Gleiche zuletzt Cl mit Cl₂ aus.",
  "ethin-h2": "C₂H₂ hat 2 H-Atome, C₂H₆ hat 6. Jedes H₂ bringt 2 mit.",
  essigsaeure: "Jedes CH₃COOH hat ein O-Atom mehr als CH₃CHO. O₂ liefert 2 O-Atome.",
  "hi-zerfall": "Beginne mit H: Vergleiche die H-Atome im HI und im H₂. Prüfe danach I.",
  "h2s-s": "S bleibt als Schwefel übrig, H geht ins Wasser. Beginne mit O: Vergleiche O₂ und H₂O.",
  formaldehyd: "Jedes CH₃OH gibt 2 H-Atome ab, die mit O zu H₂O werden. O₂ bringt 2 O-Atome.",
  // Level II · mittel
  p4: "P₄ und P₄O₁₀ haben gleich viel P. Zähle die O-Atome im P₄O₁₀ – jedes O₂ bringt 2.",
  h3po4: "Beginne mit P: Vergleiche die P-Atome im P₄O₁₀ und im H₃PO₄. Gleiche danach H aus, prüfe zuletzt O.",
  "harnstoff-syn": "Beginne mit N: Vergleiche die N-Atome im NH₃ und im CO(NH₂)₂. Prüfe danach H und O.",
  harnstoff: "In CO(NH₂)₂ gilt die 2 hinter der Klammer für N und H. Beginne mit N.",
  "essig-o2": "CH₃COOH hat 2 C, 4 H und 2 O. Zuerst C, dann H, O₂ zuletzt.",
  "ameisen-o2": "HCOOH hat selbst 2 O-Atome. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  aceton: "CH₃COCH₃ hat 3 C, 6 H und 1 O. Zuerst C, dann H, O₂ zuletzt.",
  ethanal: "Jedes C₂H₅OH gibt 2 H-Atome ab, die mit O zu H₂O werden. O₂ bringt 2 O-Atome.",
  "no2-h2o": "N steht rechts zweimal: im HNO₃ und im NO. Beginne mit H, dann N, prüfe zuletzt O.",
  "zucker-gaerung": "Beginne mit C: 12 C-Atome verteilen sich auf Ethanol (2 C) und CO₂ (1 C). Wasser liefert fehlende H.",
  // Level II · schwer
  "zucker-o2": "C₁₂H₂₂O₁₁ bringt schon 11 O-Atome mit. Zieh sie ab, bevor du O₂ bestimmst.",
  ph3: "Beginne mit P: Vergleiche PH₃ und P₂O₅. Dann H, O₂ zuletzt.",
  "nh3-no2": "N geht ins NO₂, H ins H₂O. Wähle NH₃ so, dass H₂O eine ganze Zahl bekommt.",
  "harnstoff-o2": "Harnstoff hat 1 C, 2 N, 4 H und 1 O. Zuerst C, N und H, O₂ zuletzt.",
  claus: "Gleiche zuerst O über H₂O aus, dann H. Schwefel S kommt zuletzt.",
  benzol: "C₆H₆: zuerst C, dann H, O₂ zuletzt. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  hcn: "HCN hat je ein H und ein N. H₂O und N₂ brauchen je 2 davon.",
  glycin: "NH₂CH₂COOH hat 2 C, 5 H, 1 N und 2 O. N₂ braucht 2 N-Atome.",
  dodecan: "C₁₂H₂₆: zuerst C, dann H, O₂ zuletzt. Bräuchtest du ein halbes O₂, verdopple alle Zahlen.",
  "h2s-cl2": "S geht ins H₂SO₄, O kommt nur aus H₂O, Cl nur aus Cl₂. Zuerst S und O, dann Cl.",
};

export const HINTS_EN: Record<string, string> = {
  co2: "Count C and O on both sides. Only change a number if the two sides have different numbers of atoms.",
  hf: "Compare the F atoms: F₂ on the left, HF on the right. Then check H.",
  hbr: "Compare the Br atoms: Br₂ on the left, HBr on the right. Then check H.",
  hi: "Compare the I atoms: I₂ on the left, HI on the right.",
  "ch4-syn": "CH₄ has 4 H atoms. Each H₂ supplies 2 of them.",
  "no-syn": "Compare the N atoms: N₂ on the left, NO on the right. Then check O.",
  cs2: "Count the S atoms in CS₂. On the left, sulfur is a single atom S.",
  boudouard: "Count the C atoms on the left in CO₂ and in the carbon. Then check O.",
  "n2h4-zerfall": "N₂H₄ has 4 H atoms. Each H₂ takes 2 of them.",
  "methanol-syn": "CH₃OH has 4 H atoms. Each H₂ supplies 2 of them.",
  "co-o2": "Start with C: CO and CO₂ each have one C. Then balance O with O₂.",
  ozon: "O₃ on the left, O₂ on the right. Find the smallest number of O atoms divisible by 3 and by 2.",
  "no-h2": "Start with N: compare NO and N₂. Then O, H last.",
  wasser: "Start with O: compare the O atoms in H₂O and in O₂. Then check H.",
  h2o2: "Start with H: compare the H atoms in H₂O₂ and H₂O. Balance O with O₂ last.",
  "nh3-zerfall": "Start with N: compare NH₃ and N₂. Then share out the H atoms to H₂.",
  pcl3: "Start with P: compare the P atoms in P₄ and PCl₃. Then balance Cl with Cl₂.",
  "co-syn": "Start with O: compare the O atoms in O₂ and in CO. Then check C.",
  "cs2-o2": "Share out C and S first: S only appears in SO₂ on the right. O₂ comes last.",
  p2o5: "P₂O₅ has 5 O atoms. O₂ always supplies an even number. How does the O count on the right become even?",
  ethen: "C₂H₄: C first, then H. O₂ comes last – count all O atoms on the right for it.",
  ethanol: "C₂H₅OH has 6 H atoms and one O atom of its own. Count that O on the left.",
  pentan: "C₅H₁₂: C first, then H. O₂ comes last – count all O atoms on the right for it.",
  zellatmung: "Start with C: count the C atoms in the glucose. When counting O, include the O atoms in the sugar.",
  h2s: "S goes into SO₂, H into H₂O. If you would need half an O₂, double all numbers.",
  methanol: "CH₃OH has one O atom of its own. If you would need half an O₂, double all numbers.",
  ethan: "C₂H₆: C first, then H, O₂ last. If you would need half an O₂, double all numbers.",
  ethin: "C₂H₂ has only 2 H atoms. C and H first, O₂ last. A half number means: double everything.",
  "nh3-o2": "N goes into N₂, H into H₂O. N₂ needs an even number of N atoms.",
  butan: "Balance C and H first. If the O count on the right is odd, double C₄H₁₀.",
  kontakt: "Each SO₃ has one O atom more than SO₂. O₂ supplies 2 O atoms.",
  no2: "Each NO₂ has one O atom more than NO. O₂ supplies 2 O atoms.",
  ch2cl2: "Each Cl₂ swaps one H: one Cl goes to the C, one into HCl. How many H are swapped?",
  chcl3: "Each Cl on the C replaces an H. Where does that H go? Balance Cl with Cl₂ last.",
  "ccl4-ch4": "Follow the H atoms of methane: where are they on the right? Balance Cl with Cl₂ last.",
  "ethin-h2": "C₂H₂ has 2 H atoms, C₂H₆ has 6. Each H₂ brings 2.",
  essigsaeure: "Each CH₃COOH has one O atom more than CH₃CHO. O₂ supplies 2 O atoms.",
  "hi-zerfall": "Start with H: compare the H atoms in HI and in H₂. Then check I.",
  "h2s-s": "S is left over as sulfur, H goes into water. Start with O: compare O₂ and H₂O.",
  formaldehyd: "Each CH₃OH gives off 2 H atoms, which form H₂O with O. O₂ brings 2 O atoms.",
  p4: "P₄ and P₄O₁₀ have the same number of P. Count the O atoms in P₄O₁₀ – each O₂ brings 2.",
  h3po4: "Start with P: compare the P atoms in P₄O₁₀ and in H₃PO₄. Then balance H and check O last.",
  "harnstoff-syn": "Start with N: compare the N atoms in NH₃ and in CO(NH₂)₂. Then check H and O.",
  harnstoff: "In CO(NH₂)₂ the 2 after the bracket applies to N and H. Start with N.",
  "essig-o2": "CH₃COOH has 2 C, 4 H and 2 O. C first, then H, O₂ last.",
  "ameisen-o2": "HCOOH has 2 O atoms of its own. If you would need half an O₂, double all numbers.",
  aceton: "CH₃COCH₃ has 3 C, 6 H and 1 O. C first, then H, O₂ last.",
  ethanal: "Each C₂H₅OH gives off 2 H atoms, which form H₂O with O. O₂ brings 2 O atoms.",
  "no2-h2o": "N appears twice on the right: in HNO₃ and in NO. Start with H, then N, check O last.",
  "zucker-gaerung": "Start with C: 12 C atoms are shared between ethanol (2 C) and CO₂ (1 C). Water supplies missing H.",
  "zucker-o2": "C₁₂H₂₂O₁₁ already brings 11 O atoms. Subtract them before you set O₂.",
  ph3: "Start with P: compare PH₃ and P₂O₅. Then H, O₂ last.",
  "nh3-no2": "N goes into NO₂, H into H₂O. Choose NH₃ so that H₂O gets a whole number.",
  "harnstoff-o2": "Urea has 1 C, 2 N, 4 H and 1 O. C, N and H first, O₂ last.",
  claus: "Balance O first using H₂O, then H. Sulfur S comes last.",
  benzol: "C₆H₆: C first, then H, O₂ last. If you would need half an O₂, double all numbers.",
  hcn: "HCN has one H and one N. H₂O and N₂ each need 2 of them.",
  glycin: "NH₂CH₂COOH has 2 C, 5 H, 1 N and 2 O. N₂ needs 2 N atoms.",
  dodecan: "C₁₂H₂₆: C first, then H, O₂ last. If you would need half an O₂, double all numbers.",
  "h2s-cl2": "S goes into H₂SO₄, O comes only from H₂O, Cl only from Cl₂. S and O first, then Cl.",
};

export const HINTS: Record<string, string> = tr(HINTS_DE, HINTS_EN);
