// Fehlvorstellungen (Stolpersteine) zur Neutralisation – Schlüssel für diagnostische Distraktoren und Fallen im Baukasten.
// Die Rückmeldungstexte stehen bei den Aufgaben (mit den konkreten Stoffen); hier nur der Name für Landkarte und Auswertung.
import { tr } from "@lern/i18n";

const MISS_DE: Record<string, string> = {
  "index-als-ladung": "Index als Ladung gelesen (H₂⁺ statt 2 H⁺)",
  "ohne-ladung": "Beim Zerfall neutrale Atome statt Ionen",
  "rest-ladung-eins": "Säurerest immer 1−",
  "ein-proton": "Jede Säure gibt nur 1 H⁺ ab",
  "atome-statt-h": "Alle Atome statt der H-Atome gezählt",
  "rest-verwechselt": "Säurerest einer ähnlichen Säure",
  "rest-ladung-vorzeichen": "Säurerest positiv geladen",
  "rest-ladung-sauerstoff": "Ladung aus der Zahl der O-Atome",
  "alle-h-sauer": "Alle H-Atome als abgebbar gezählt",
  "endung-id-at-it": "Endungen -id / -it / -at verwechselt",
  "rest-aus-saeurename": "Säurerest-Name aus dem Säurenamen gebildet",
  "saeurename-statt-rest": "Säurename statt Säurerest",
  "hydrogen-verzaehlt": "Hydrogen / Dihydrogen verzählt",
  "stufe-ignoriert": "Teilweise Abgabe von H⁺ übersehen",
  "oh-zusammengefasst": "OH⁻-Ionen zu OH₂ zusammengefasst",
  "oh-zerlegt": "OH⁻ in O und H zerlegt",
  "lauge-gibt-h": "Lauge gibt H⁺ ab",
  "kation-ladung": "Ladung des Metall-Ions verzählt",
  "ein-wasser": "Immer nur 1 H₂O",
  "wasser-summe": "Zahlen vor Lauge und Säure als Zahl der H₂O addiert",
  "wasser-als-koeffizient": "Zahl der H₂O als Koeffizient genommen",
  "eine-formeleinheit": "Zahl vor Lauge bzw. Säure übersehen",
  "ladung-statt-anzahl": "H⁺ bzw. OH⁻ je Formeleinheit statt Anzahl der Formeleinheiten",
  "index-aus-formel": "Index aus Säure oder Hydroxid ins Salz übernommen",
  "wasser-atome": "H₂O aus H-Atomen statt aus H⁺ + OH⁻",
  "wasser-vergessen": "Wasser als Produkt vergessen",
  "salz-1zu1": "Salz immer 1 : 1",
  "indizes-vertauscht": "Indizes im Salz vertauscht",
  "klammer-vergessen": "Klammer um mehratomiges Ion vergessen",
  "h-im-salz": "H der Säure im Salz gelassen",
  "edukt-statt-salz": "Hydroxid statt Salz gewählt",
  "koeff-1zu1": "Immer 1 Lauge + 1 Säure",
  "koeff-vertauscht": "Koeffizienten von Lauge und Säure vertauscht",
  "nicht-gekuerzt": "Verhältnis nicht gekürzt",
  "ladung-verzaehlt": "Ladung des Säurerests verzählt",
  "h-verzaehlt": "Zahl der abgebbaren H⁺ verzählt",
  "wasser-verzaehlt": "Zahl der H₂O verzählt",
  "koeff-verzaehlt": "Koeffizient verzählt (OH⁻ und H⁺ nicht gleich viele)",
  "anderer-rest": "Säurerest einer anderen Säure",
};
const MISS_EN: Record<string, string> = {
  "index-als-ladung": "Subscript read as charge (H₂⁺ instead of 2 H⁺)",
  "ohne-ladung": "Neutral atoms instead of ions on dissociation",
  "rest-ladung-eins": "Acid anion always 1−",
  "ein-proton": "Every acid gives off only 1 H⁺",
  "atome-statt-h": "All atoms counted instead of the H atoms",
  "rest-verwechselt": "Acid anion of a similar acid",
  "rest-ladung-vorzeichen": "Acid anion positively charged",
  "rest-ladung-sauerstoff": "Charge taken from the number of O atoms",
  "alle-h-sauer": "All H atoms counted as acidic",
  "endung-id-at-it": "Endings -ide / -ite / -ate confused",
  "rest-aus-saeurename": "Anion name made from the acid name",
  "saeurename-statt-rest": "Acid name instead of acid anion",
  "hydrogen-verzaehlt": "Hydrogen / dihydrogen miscounted",
  "stufe-ignoriert": "Partial release of H⁺ overlooked",
  "oh-zusammengefasst": "OH⁻ ions combined into OH₂",
  "oh-zerlegt": "OH⁻ split into O and H",
  "lauge-gibt-h": "Alkali gives off H⁺",
  "kation-ladung": "Charge of the metal ion miscounted",
  "ein-wasser": "Always only 1 H₂O",
  "wasser-summe": "Numbers of alkali and acid added up as the number of H₂O",
  "wasser-als-koeffizient": "Number of H₂O taken as the coefficient",
  "eine-formeleinheit": "Number in front of alkali or acid overlooked",
  "ladung-statt-anzahl": "H⁺ or OH⁻ per formula unit instead of number of formula units",
  "index-aus-formel": "Subscript taken from the acid or hydroxide into the salt",
  "wasser-atome": "H₂O from H atoms instead of H⁺ + OH⁻",
  "wasser-vergessen": "Water forgotten as a product",
  "salz-1zu1": "Salt always 1 : 1",
  "indizes-vertauscht": "Subscripts swapped in the salt",
  "klammer-vergessen": "Brackets around polyatomic ion forgotten",
  "h-im-salz": "H of the acid left in the salt",
  "edukt-statt-salz": "Hydroxide chosen instead of salt",
  "koeff-1zu1": "Always 1 alkali + 1 acid",
  "koeff-vertauscht": "Coefficients of alkali and acid swapped",
  "nicht-gekuerzt": "Ratio not simplified",
  "ladung-verzaehlt": "Charge of the acid anion miscounted",
  "h-verzaehlt": "Number of H⁺ given off miscounted",
  "wasser-verzaehlt": "Number of H₂O miscounted",
  "koeff-verzaehlt": "Coefficient miscounted (OH⁻ and H⁺ not equal)",
  "anderer-rest": "Acid anion of a different acid",
};
export const MISS = tr(MISS_DE, MISS_EN);
