// Fehlvorstellungen (Stolpersteine) zu Polymeren – Schlüssel für diagnostische Distraktoren und Fallen. Die Rückmeldungstexte
// stehen bei den Aufgaben (mit den konkreten Stoffen); hier nur der Name für Landkarte und Auswertung.
import { tr } from "@lern/i18n";

const MISS_DE: Record<string, string> = {
  // Monomere und Polymere
  "doppelbindung-fehlt": "Gesättigtes Molekül für Monomer gehalten",
  "doppelbindung-bleibt": "Zweifachbindung im Baustein behalten",
  "name-verwechselt": "Monomer und Polymer verwechselt",
  "n-stickstoff": "n in der Formel für Stickstoff gehalten",
  "atome-statt-bausteine": "Atome statt Bausteine gezählt",
  "bindungen-gezaehlt": "Bindungen statt Bausteine gezählt",
  "gruppe-verwechselt": "Seitengruppe falsch zugeordnet",
  "verwendung-verwechselt": "Kunststoff und Verwendung verwechselt",
  // radikalische Polymerisation
  "radikal-ion": "Radikal für Ion gehalten",
  "homolyse-heterolyse": "Bindungsbruch mit Ionenbildung verwechselt",
  "pfeil-paar": "Halber Pfeil für Elektronenpaar gehalten",
  "schritt-verwechselt": "Start, Wachstum und Abbruch verwechselt",
  "radikal-bleibt": "Radikal bleibt am Anfang der Kette",
  "abbruch-verwechselt": "Rekombination und Disproportionierung verwechselt",
  "starter-katalysator": "Starter für Katalysator gehalten",
  "mehr-starter-laenger": "Mehr Starter für längere Ketten gehalten",
  // Katalysatoren und Verfahren
  "zn-radikal": "Einbau am Titan mit Radikal verwechselt",
  "zn-polar": "Polares Monomer für Ziegler-Natta gehalten",
  "zn-unpolar-gift": "Unpolares Monomer für Gift gehalten",
  "taktisch-verwechselt": "Taktizität verwechselt",
  "radikal-taktisch": "Radikalische Ketten für geordnet gehalten",
  "verzweigt-dichte": "Verzweigte Ketten für dichter gehalten",
  "block-getrennt": "Lebende Ketten und Abbruch verwechselt",
  "kation-polar": "Elektronen ziehende Gruppe für kationisch gehalten",
  "verfahren-passt-nicht": "Verfahren passt nicht zum Monomer",
  // Polykondensation und Polyaddition
  "gleiche-gruppen": "Gleiche Gruppen sollen reagieren",
  "kond-doppelbindung": "Polykondensation mit Zweifachbindung verwechselt",
  "byp-falsch": "Falsches Nebenprodukt",
  "byp-chlorid": "Wasser statt HCl beim Säurechlorid",
  "ester-amid": "Ester- und Amidbindung verwechselt",
  "schnitt-falsch": "Falsch geschnitten (alte Bindung für neu gehalten)",
  "funktionalitaet-eins": "Eine Gruppe reicht für eine Kette",
  "netz-funktionalitaet": "Drei Gruppen für lineare Ketten gehalten",
  "add-wasser": "Nebenprodukt bei Polyaddition vermutet",
  "ester-urethan": "Urethan- und Esterbindung verwechselt",
  "art-verwechselt": "Polykondensation und Polyaddition verwechselt",
  "h-wandert-falsch": "Falsches Atom wandert",
  "verknuepfungen-gezaehlt": "Monomere statt Verknüpfungen gezählt",
  // Struktur und Eigenschaften
  "netz-schmilzt": "Duroplast für schmelzbar gehalten",
  "elast-thermo": "Elastomer und Thermoplast verwechselt",
  "elast-duro": "Elastomer und Duroplast verwechselt",
  "thermo-duro": "Einzelne Ketten für ein Netz gehalten",
  "copo-verwechselt": "Art des Copolymers verwechselt",
  "kette-sofort": "Lange Ketten beim Stufenwachstum sofort erwartet",
  "kette-spaet": "Lange Ketten beim Kettenwachstum erst spät erwartet",
};
const MISS_EN: Record<string, string> = {
  "doppelbindung-fehlt": "Saturated molecule taken for a monomer",
  "doppelbindung-bleibt": "Double bond kept in the unit",
  "name-verwechselt": "Monomer and polymer mixed up",
  "n-stickstoff": "n in the formula taken for nitrogen",
  "atome-statt-bausteine": "Counted atoms instead of units",
  "bindungen-gezaehlt": "Counted bonds instead of units",
  "gruppe-verwechselt": "Side group assigned wrongly",
  "verwendung-verwechselt": "Plastic and its use mixed up",
  "radikal-ion": "Radical taken for an ion",
  "homolyse-heterolyse": "Bond breaking confused with ion formation",
  "pfeil-paar": "Half-headed arrow taken for an electron pair",
  "schritt-verwechselt": "Initiation, propagation and termination mixed up",
  "radikal-bleibt": "Radical stays at the start of the chain",
  "abbruch-verwechselt": "Combination and disproportionation mixed up",
  "starter-katalysator": "Initiator taken for a catalyst",
  "mehr-starter-laenger": "More initiator thought to give longer chains",
  "zn-radikal": "Insertion at titanium confused with a radical",
  "zn-polar": "Polar monomer thought fine for Ziegler–Natta",
  "zn-unpolar-gift": "Non-polar monomer taken for a poison",
  "taktisch-verwechselt": "Tacticity mixed up",
  "radikal-taktisch": "Radical chains thought to be ordered",
  "verzweigt-dichte": "Branched chains thought to be denser",
  "block-getrennt": "Living chains and termination mixed up",
  "kation-polar": "Electron-withdrawing group thought to suit cationic",
  "verfahren-passt-nicht": "Method does not suit the monomer",
  "gleiche-gruppen": "Identical groups expected to react",
  "kond-doppelbindung": "Polycondensation confused with a double bond",
  "byp-falsch": "Wrong by-product",
  "byp-chlorid": "Water instead of HCl with the acyl chloride",
  "ester-amid": "Ester and amide bond mixed up",
  "schnitt-falsch": "Cut in the wrong place (old bond taken as new)",
  "funktionalitaet-eins": "One group thought enough for a chain",
  "netz-funktionalitaet": "Three groups thought to give linear chains",
  "add-wasser": "By-product expected in polyaddition",
  "ester-urethan": "Urethane and ester bond mixed up",
  "art-verwechselt": "Polycondensation and polyaddition mixed up",
  "h-wandert-falsch": "Wrong atom moves",
  "verknuepfungen-gezaehlt": "Counted monomers instead of links",
  "netz-schmilzt": "Thermoset thought to melt",
  "elast-thermo": "Elastomer and thermoplastic mixed up",
  "elast-duro": "Elastomer and thermoset mixed up",
  "thermo-duro": "Separate chains taken for a network",
  "copo-verwechselt": "Type of copolymer mixed up",
  "kette-sofort": "Long chains expected early in step growth",
  "kette-spaet": "Long chains expected late in chain growth",
};
export const MISS = tr(MISS_DE, MISS_EN);
